{
  "uid" : "1c829f0112cce216",
  "name" : "Select a random card from \"Слова с частотной группировкой\" group and compare UI vs BACKEND data.",
  "fullName" : "tests.test_speech_exercises_ru.TestCardsRU#test_random_cards_in_words_with_frequency_grouping_ru",
  "historyId" : "27fd1e44aaf197b141c2f0bb01434dcd",
  "time" : {
    "start" : 1728784243501,
    "stop" : 1728784243501,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x561d2329d02a <unknown>\n#1 0x561d22f835e0 <unknown>\n#2 0x561d22f7b7eb <unknown>\n#3 0x561d22f6ba09 <unknown>\n#4 0x561d22f6d744 <unknown>\n#5 0x561d22f6bcbd <unknown>\n#6 0x561d22f6b52f <unknown>\n#7 0x561d22f6b422 <unknown>\n#8 0x561d22f69493 <unknown>\n#9 0x561d22f69ada <unknown>\n#10 0x561d22f85f41 <unknown>\n#11 0x561d230178c5 <unknown>\n#12 0x561d22ff7b22 <unknown>\n#13 0x561d23016d7d <unknown>\n#14 0x561d22ff78c3 <unknown>\n#15 0x561d22fc56b3 <unknown>\n#16 0x561d22fc668e <unknown>\n#17 0x561d23267a2b <unknown>\n#18 0x561d2326b9b1 <unknown>\n#19 0x561d23254225 <unknown>\n#20 0x561d2326c532 <unknown>\n#21 0x561d2323938f <unknown>\n#22 0x561d2328bf28 <unknown>\n#23 0x561d2328c0f3 <unknown>\n#24 0x561d2329be7c <unknown>\n#25 0x7f8348c94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"eb6f7288274469725cfba4103cd954b6\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7faf1f5fac90>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x561d2328c0f3 \\\\u003Cunknown>\\\\n#24 0x561d2329be7c \\\\u003Cunknown>\\\\n#25 0x7f8348c94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x561d2329d02a <unknown>\nE       #1 0x561d22f835e0 <unknown>\nE       #2 0x561d22f7b7eb <unknown>\nE       #3 0x561d22f6ba09 <unknown>\nE       #4 0x561d22f6d744 <unknown>\nE       #5 0x561d22f6bcbd <unknown>\nE       #6 0x561d22f6b52f <unknown>\nE       #7 0x561d22f6b422 <unknown>\nE       #8 0x561d22f69493 <unknown>\nE       #9 0x561d22f69ada <unknown>\nE       #10 0x561d22f85f41 <unknown>\nE       #11 0x561d230178c5 <unknown>\nE       #12 0x561d22ff7b22 <unknown>\nE       #13 0x561d23016d7d <unknown>\nE       #14 0x561d22ff78c3 <unknown>\nE       #15 0x561d22fc56b3 <unknown>\nE       #16 0x561d22fc668e <unknown>\nE       #17 0x561d23267a2b <unknown>\nE       #18 0x561d2326b9b1 <unknown>\nE       #19 0x561d23254225 <unknown>\nE       #20 0x561d2326c532 <unknown>\nE       #21 0x561d2323938f <unknown>\nE       #22 0x561d2328bf28 <unknown>\nE       #23 0x561d2328c0f3 <unknown>\nE       #24 0x561d2329be7c <unknown>\nE       #25 0x7f8348c94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728784244276,
      "stop" : 1728784244698,
      "duration" : 422
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x561d2329d02a <unknown>\n#1 0x561d22f835e0 <unknown>\n#2 0x561d22f7b7eb <unknown>\n#3 0x561d22f6ba09 <unknown>\n#4 0x561d22f6d744 <unknown>\n#5 0x561d22f6bcbd <unknown>\n#6 0x561d22f6b52f <unknown>\n#7 0x561d22f6b422 <unknown>\n#8 0x561d22f69493 <unknown>\n#9 0x561d22f69ada <unknown>\n#10 0x561d22f85f41 <unknown>\n#11 0x561d230178c5 <unknown>\n#12 0x561d22ff7b22 <unknown>\n#13 0x561d23016d7d <unknown>\n#14 0x561d22ff78c3 <unknown>\n#15 0x561d22fc56b3 <unknown>\n#16 0x561d22fc668e <unknown>\n#17 0x561d23267a2b <unknown>\n#18 0x561d2326b9b1 <unknown>\n#19 0x561d23254225 <unknown>\n#20 0x561d2326c532 <unknown>\n#21 0x561d2323938f <unknown>\n#22 0x561d2328bf28 <unknown>\n#23 0x561d2328c0f3 <unknown>\n#24 0x561d2329be7c <unknown>\n#25 0x7f8348c94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728784244276,
        "stop" : 1728784244698,
        "duration" : 422
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x561d2329d02a <unknown>\n#1 0x561d22f835e0 <unknown>\n#2 0x561d22f7b7eb <unknown>\n#3 0x561d22f6ba09 <unknown>\n#4 0x561d22f6d744 <unknown>\n#5 0x561d22f6bcbd <unknown>\n#6 0x561d22f6b52f <unknown>\n#7 0x561d22f6b422 <unknown>\n#8 0x561d22f69493 <unknown>\n#9 0x561d22f69ada <unknown>\n#10 0x561d22f85f41 <unknown>\n#11 0x561d230178c5 <unknown>\n#12 0x561d22ff7b22 <unknown>\n#13 0x561d23016d7d <unknown>\n#14 0x561d22ff78c3 <unknown>\n#15 0x561d22fc56b3 <unknown>\n#16 0x561d22fc668e <unknown>\n#17 0x561d23267a2b <unknown>\n#18 0x561d2326b9b1 <unknown>\n#19 0x561d23254225 <unknown>\n#20 0x561d2326c532 <unknown>\n#21 0x561d2323938f <unknown>\n#22 0x561d2328bf28 <unknown>\n#23 0x561d2328c0f3 <unknown>\n#24 0x561d2329be7c <unknown>\n#25 0x7f8348c94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"eb6f7288274469725cfba4103cd954b6\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728784074935,
      "stop" : 1728784074936,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728784243501,
      "stop" : 1728784244275,
      "duration" : 774
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728784244731,
      "stop" : 1728784244793,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Speech exercises."
  }, {
    "name" : "suite",
    "value" : "Речевые упражнения."
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "subSuite",
    "value" : "TestCardsRU"
  }, {
    "name" : "host",
    "value" : "fv-az891-551"
  }, {
    "name" : "thread",
    "value" : "2367-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_speech_exercises_ru"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 5,
        "passed" : 56,
        "unknown" : 0,
        "total" : 61
      },
      "items" : [ {
        "uid" : "f0bd40d44dc354f9",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/60//#testresult/f0bd40d44dc354f9",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55b5c57a402a <unknown>\n#1 0x55b5c548a5e0 <unknown>\n#2 0x55b5c54827eb <unknown>\n#3 0x55b5c5472a09 <unknown>\n#4 0x55b5c5474744 <unknown>\n#5 0x55b5c5472cbd <unknown>\n#6 0x55b5c547252f <unknown>\n#7 0x55b5c5472422 <unknown>\n#8 0x55b5c5470493 <unknown>\n#9 0x55b5c5470ada <unknown>\n#10 0x55b5c548cf41 <unknown>\n#11 0x55b5c551e8c5 <unknown>\n#12 0x55b5c54feb22 <unknown>\n#13 0x55b5c551dd7d <unknown>\n#14 0x55b5c54fe8c3 <unknown>\n#15 0x55b5c54cc6b3 <unknown>\n#16 0x55b5c54cd68e <unknown>\n#17 0x55b5c576ea2b <unknown>\n#18 0x55b5c57729b1 <unknown>\n#19 0x55b5c575b225 <unknown>\n#20 0x55b5c5773532 <unknown>\n#21 0x55b5c574038f <unknown>\n#22 0x55b5c5792f28 <unknown>\n#23 0x55b5c57930f3 <unknown>\n#24 0x55b5c57a2e7c <unknown>\n#25 0x7ff7ef494ac3 <unknown>",
        "time" : {
          "start" : 1728697357486,
          "stop" : 1728697357486,
          "duration" : 0
        }
      }, {
        "uid" : "ff7c5eb14f6b9991",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/ff7c5eb14f6b9991",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x559ba0a4b02a <unknown>\n#1 0x559ba07315e0 <unknown>\n#2 0x559ba07297eb <unknown>\n#3 0x559ba0719a09 <unknown>\n#4 0x559ba071b744 <unknown>\n#5 0x559ba0719cbd <unknown>\n#6 0x559ba071952f <unknown>\n#7 0x559ba0719422 <unknown>\n#8 0x559ba0717493 <unknown>\n#9 0x559ba0717ada <unknown>\n#10 0x559ba0733f41 <unknown>\n#11 0x559ba07c58c5 <unknown>\n#12 0x559ba07a5b22 <unknown>\n#13 0x559ba07c4d7d <unknown>\n#14 0x559ba07a58c3 <unknown>\n#15 0x559ba07736b3 <unknown>\n#16 0x559ba077468e <unknown>\n#17 0x559ba0a15a2b <unknown>\n#18 0x559ba0a199b1 <unknown>\n#19 0x559ba0a02225 <unknown>\n#20 0x559ba0a1a532 <unknown>\n#21 0x559ba09e738f <unknown>\n#22 0x559ba0a39f28 <unknown>\n#23 0x559ba0a3a0f3 <unknown>\n#24 0x559ba0a49e7c <unknown>\n#25 0x7f8a4e894ac3 <unknown>",
        "time" : {
          "start" : 1728611048724,
          "stop" : 1728611048724,
          "duration" : 0
        }
      }, {
        "uid" : "b9a094c6992cb493",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/b9a094c6992cb493",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728525214497,
          "stop" : 1728525224653,
          "duration" : 10156
        }
      }, {
        "uid" : "5f45ff40c80462fa",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/5f45ff40c80462fa",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728438883318,
          "stop" : 1728438892894,
          "duration" : 9576
        }
      }, {
        "uid" : "5602411258f703e5",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/5602411258f703e5",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728352484457,
          "stop" : 1728352494835,
          "duration" : 10378
        }
      }, {
        "uid" : "6ab8bac834268f95",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/6ab8bac834268f95",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728267310876,
          "stop" : 1728267310876,
          "duration" : 0
        }
      }, {
        "uid" : "dcb9a9190cc9d7f6",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/dcb9a9190cc9d7f6",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728180022738,
          "stop" : 1728180033206,
          "duration" : 10468
        }
      }, {
        "uid" : "5cc1f550a42b9d4e",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/5cc1f550a42b9d4e",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728093300260,
          "stop" : 1728093311382,
          "duration" : 11122
        }
      }, {
        "uid" : "2e7fad7ac2b93b46",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/2e7fad7ac2b93b46",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728007004498,
          "stop" : 1728007016083,
          "duration" : 11585
        }
      }, {
        "uid" : "fbff2ce01a8cd1db",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/fbff2ce01a8cd1db",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727920762702,
          "stop" : 1727920774548,
          "duration" : 11846
        }
      }, {
        "uid" : "435bbe2c3522585d",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/435bbe2c3522585d",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727834140792,
          "stop" : 1727834152951,
          "duration" : 12159
        }
      }, {
        "uid" : "a4a754c68caf87e1",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/a4a754c68caf87e1",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727748255359,
          "stop" : 1727748267912,
          "duration" : 12553
        }
      }, {
        "uid" : "9a828e6e96ba0b39",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/9a828e6e96ba0b39",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727661532779,
          "stop" : 1727661543073,
          "duration" : 10294
        }
      }, {
        "uid" : "b8a69847dfba8b70",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/b8a69847dfba8b70",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727575444257,
          "stop" : 1727575457822,
          "duration" : 13565
        }
      }, {
        "uid" : "d079c3ef259901b2",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/d079c3ef259901b2",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727488648177,
          "stop" : 1727488667751,
          "duration" : 19574
        }
      }, {
        "uid" : "c131a28c2a211984",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/c131a28c2a211984",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727402397810,
          "stop" : 1727402411834,
          "duration" : 14024
        }
      }, {
        "uid" : "a598953560b062b3",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/a598953560b062b3",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727315930964,
          "stop" : 1727315945439,
          "duration" : 14475
        }
      }, {
        "uid" : "8a157af3ade28ef8",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/8a157af3ade28ef8",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727229600257,
          "stop" : 1727229615914,
          "duration" : 15657
        }
      }, {
        "uid" : "7a7fec4dc3ec6e08",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/7a7fec4dc3ec6e08",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727143002724,
          "stop" : 1727143047515,
          "duration" : 44791
        }
      }, {
        "uid" : "1b5c8cf5369841a1",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/1b5c8cf5369841a1",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//button[@title=\"Слова с частотной группировкой\"]')\nStacktrace:\n#0 0x55a75f07e2da <unknown>\n#1 0x55a75ed4c200 <unknown>\n#2 0x55a75ed9baa2 <unknown>\n#3 0x55a75ed9bd41 <unknown>\n#4 0x55a75ede1964 <unknown>\n#5 0x55a75edc08fd <unknown>\n#6 0x55a75eddedfd <unknown>\n#7 0x55a75edc0673 <unknown>\n#8 0x55a75ed8e473 <unknown>\n#9 0x55a75ed8f47e <unknown>\n#10 0x55a75f0450db <unknown>\n#11 0x55a75f049071 <unknown>\n#12 0x55a75f0319d5 <unknown>\n#13 0x55a75f049bf2 <unknown>\n#14 0x55a75f016b6f <unknown>\n#15 0x55a75f06d248 <unknown>\n#16 0x55a75f06d417 <unknown>\n#17 0x55a75f07d0cc <unknown>\n#18 0x7efdec894ac3 <unknown>",
        "time" : {
          "start" : 1727056438138,
          "stop" : 1727056461328,
          "duration" : 23190
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail" ]
  },
  "source" : "1c829f0112cce216.json",
  "parameterValues" : [ ]
}