{
  "uid" : "1f05c25385384319",
  "name" : "Verify sizes of icons in sections",
  "fullName" : "tests.used_resources_page_test.TestUsedResourcesPageForAuthorizedUserIcons#test_ur_04_02_verify_icons_sizes",
  "historyId" : "15f8add603fadd323dc4269b62f77d8a",
  "time" : {
    "start" : 1728784261571,
    "stop" : 1728784261571,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x559da95b402a <unknown>\n#1 0x559da929a5e0 <unknown>\n#2 0x559da92927eb <unknown>\n#3 0x559da9282a09 <unknown>\n#4 0x559da9284744 <unknown>\n#5 0x559da9282cbd <unknown>\n#6 0x559da928252f <unknown>\n#7 0x559da9282422 <unknown>\n#8 0x559da9280493 <unknown>\n#9 0x559da9280ada <unknown>\n#10 0x559da929cf41 <unknown>\n#11 0x559da932e8c5 <unknown>\n#12 0x559da930eb22 <unknown>\n#13 0x559da932dd7d <unknown>\n#14 0x559da930e8c3 <unknown>\n#15 0x559da92dc6b3 <unknown>\n#16 0x559da92dd68e <unknown>\n#17 0x559da957ea2b <unknown>\n#18 0x559da95829b1 <unknown>\n#19 0x559da956b225 <unknown>\n#20 0x559da9583532 <unknown>\n#21 0x559da955038f <unknown>\n#22 0x559da95a2f28 <unknown>\n#23 0x559da95a30f3 <unknown>\n#24 0x559da95b2e7c <unknown>\n#25 0x7f6794a94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c519d2bb93f8f16375a989c4e3cb94f6\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7faf1f712f90>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x559da95a30f3 \\\\u003Cunknown>\\\\n#24 0x559da95b2e7c \\\\u003Cunknown>\\\\n#25 0x7f6794a94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x559da95b402a <unknown>\nE       #1 0x559da929a5e0 <unknown>\nE       #2 0x559da92927eb <unknown>\nE       #3 0x559da9282a09 <unknown>\nE       #4 0x559da9284744 <unknown>\nE       #5 0x559da9282cbd <unknown>\nE       #6 0x559da928252f <unknown>\nE       #7 0x559da9282422 <unknown>\nE       #8 0x559da9280493 <unknown>\nE       #9 0x559da9280ada <unknown>\nE       #10 0x559da929cf41 <unknown>\nE       #11 0x559da932e8c5 <unknown>\nE       #12 0x559da930eb22 <unknown>\nE       #13 0x559da932dd7d <unknown>\nE       #14 0x559da930e8c3 <unknown>\nE       #15 0x559da92dc6b3 <unknown>\nE       #16 0x559da92dd68e <unknown>\nE       #17 0x559da957ea2b <unknown>\nE       #18 0x559da95829b1 <unknown>\nE       #19 0x559da956b225 <unknown>\nE       #20 0x559da9583532 <unknown>\nE       #21 0x559da955038f <unknown>\nE       #22 0x559da95a2f28 <unknown>\nE       #23 0x559da95a30f3 <unknown>\nE       #24 0x559da95b2e7c <unknown>\nE       #25 0x7f6794a94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728784074935,
      "stop" : 1728784074936,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728784261571,
      "stop" : 1728784262340,
      "duration" : 769
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728784262340,
      "stop" : 1728784262763,
      "duration" : 423
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x559da95b402a <unknown>\n#1 0x559da929a5e0 <unknown>\n#2 0x559da92927eb <unknown>\n#3 0x559da9282a09 <unknown>\n#4 0x559da9284744 <unknown>\n#5 0x559da9282cbd <unknown>\n#6 0x559da928252f <unknown>\n#7 0x559da9282422 <unknown>\n#8 0x559da9280493 <unknown>\n#9 0x559da9280ada <unknown>\n#10 0x559da929cf41 <unknown>\n#11 0x559da932e8c5 <unknown>\n#12 0x559da930eb22 <unknown>\n#13 0x559da932dd7d <unknown>\n#14 0x559da930e8c3 <unknown>\n#15 0x559da92dc6b3 <unknown>\n#16 0x559da92dd68e <unknown>\n#17 0x559da957ea2b <unknown>\n#18 0x559da95829b1 <unknown>\n#19 0x559da956b225 <unknown>\n#20 0x559da9583532 <unknown>\n#21 0x559da955038f <unknown>\n#22 0x559da95a2f28 <unknown>\n#23 0x559da95a30f3 <unknown>\n#24 0x559da95b2e7c <unknown>\n#25 0x7f6794a94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728784262340,
        "stop" : 1728784262762,
        "duration" : 422
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x559da95b402a <unknown>\n#1 0x559da929a5e0 <unknown>\n#2 0x559da92927eb <unknown>\n#3 0x559da9282a09 <unknown>\n#4 0x559da9284744 <unknown>\n#5 0x559da9282cbd <unknown>\n#6 0x559da928252f <unknown>\n#7 0x559da9282422 <unknown>\n#8 0x559da9280493 <unknown>\n#9 0x559da9280ada <unknown>\n#10 0x559da929cf41 <unknown>\n#11 0x559da932e8c5 <unknown>\n#12 0x559da930eb22 <unknown>\n#13 0x559da932dd7d <unknown>\n#14 0x559da930e8c3 <unknown>\n#15 0x559da92dc6b3 <unknown>\n#16 0x559da92dd68e <unknown>\n#17 0x559da957ea2b <unknown>\n#18 0x559da95829b1 <unknown>\n#19 0x559da956b225 <unknown>\n#20 0x559da9583532 <unknown>\n#21 0x559da955038f <unknown>\n#22 0x559da95a2f28 <unknown>\n#23 0x559da95a30f3 <unknown>\n#24 0x559da95b2e7c <unknown>\n#25 0x7f6794a94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"c519d2bb93f8f16375a989c4e3cb94f6\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728784262795,
      "stop" : 1728784262858,
      "duration" : 63
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Used Resources Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "used_resources_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestUsedResourcesPage"
  }, {
    "name" : "host",
    "value" : "fv-az891-551"
  }, {
    "name" : "thread",
    "value" : "2367-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.used_resources_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 30,
        "unknown" : 0,
        "total" : 34
      },
      "items" : [ {
        "uid" : "37d808a4c8b2bb06",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/60//#testresult/37d808a4c8b2bb06",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5598df98502a <unknown>\n#1 0x5598df66b5e0 <unknown>\n#2 0x5598df6637eb <unknown>\n#3 0x5598df653a09 <unknown>\n#4 0x5598df655744 <unknown>\n#5 0x5598df653cbd <unknown>\n#6 0x5598df65352f <unknown>\n#7 0x5598df653422 <unknown>\n#8 0x5598df651493 <unknown>\n#9 0x5598df651ada <unknown>\n#10 0x5598df66df41 <unknown>\n#11 0x5598df6ff8c5 <unknown>\n#12 0x5598df6dfb22 <unknown>\n#13 0x5598df6fed7d <unknown>\n#14 0x5598df6df8c3 <unknown>\n#15 0x5598df6ad6b3 <unknown>\n#16 0x5598df6ae68e <unknown>\n#17 0x5598df94fa2b <unknown>\n#18 0x5598df9539b1 <unknown>\n#19 0x5598df93c225 <unknown>\n#20 0x5598df954532 <unknown>\n#21 0x5598df92138f <unknown>\n#22 0x5598df973f28 <unknown>\n#23 0x5598df9740f3 <unknown>\n#24 0x5598df983e7c <unknown>\n#25 0x7f48d3c94ac3 <unknown>",
        "time" : {
          "start" : 1728697375616,
          "stop" : 1728697375616,
          "duration" : 0
        }
      }, {
        "uid" : "73a24a18c48b3aa0",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/73a24a18c48b3aa0",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55b53d1b102a <unknown>\n#1 0x55b53ce975e0 <unknown>\n#2 0x55b53ce8f7eb <unknown>\n#3 0x55b53ce7fa09 <unknown>\n#4 0x55b53ce81744 <unknown>\n#5 0x55b53ce7fcbd <unknown>\n#6 0x55b53ce7f52f <unknown>\n#7 0x55b53ce7f422 <unknown>\n#8 0x55b53ce7d493 <unknown>\n#9 0x55b53ce7dada <unknown>\n#10 0x55b53ce99f41 <unknown>\n#11 0x55b53cf2b8c5 <unknown>\n#12 0x55b53cf0bb22 <unknown>\n#13 0x55b53cf2ad7d <unknown>\n#14 0x55b53cf0b8c3 <unknown>\n#15 0x55b53ced96b3 <unknown>\n#16 0x55b53ceda68e <unknown>\n#17 0x55b53d17ba2b <unknown>\n#18 0x55b53d17f9b1 <unknown>\n#19 0x55b53d168225 <unknown>\n#20 0x55b53d180532 <unknown>\n#21 0x55b53d14d38f <unknown>\n#22 0x55b53d19ff28 <unknown>\n#23 0x55b53d1a00f3 <unknown>\n#24 0x55b53d1afe7c <unknown>\n#25 0x7f0138c94ac3 <unknown>",
        "time" : {
          "start" : 1728611066833,
          "stop" : 1728611066833,
          "duration" : 0
        }
      }, {
        "uid" : "a9d59bab4d6363d7",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/a9d59bab4d6363d7",
        "status" : "passed",
        "time" : {
          "start" : 1728525402531,
          "stop" : 1728525403357,
          "duration" : 826
        }
      }, {
        "uid" : "100e8ef3c367a14b",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/100e8ef3c367a14b",
        "status" : "passed",
        "time" : {
          "start" : 1728439239977,
          "stop" : 1728439240802,
          "duration" : 825
        }
      }, {
        "uid" : "daebe55580581385",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/daebe55580581385",
        "status" : "passed",
        "time" : {
          "start" : 1728352676839,
          "stop" : 1728352677678,
          "duration" : 839
        }
      }, {
        "uid" : "fa27a9890ce02f",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/fa27a9890ce02f",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728267947385,
          "stop" : 1728267947385,
          "duration" : 0
        }
      }, {
        "uid" : "eb97d65f9bd8c15a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/eb97d65f9bd8c15a",
        "status" : "passed",
        "time" : {
          "start" : 1728180210348,
          "stop" : 1728180211189,
          "duration" : 841
        }
      }, {
        "uid" : "a9c399118f053cd4",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/a9c399118f053cd4",
        "status" : "passed",
        "time" : {
          "start" : 1728093514783,
          "stop" : 1728093515677,
          "duration" : 894
        }
      }, {
        "uid" : "a05f43eab36952d2",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/a05f43eab36952d2",
        "status" : "passed",
        "time" : {
          "start" : 1728007220497,
          "stop" : 1728007221391,
          "duration" : 894
        }
      }, {
        "uid" : "2098089bdc76f730",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/2098089bdc76f730",
        "status" : "passed",
        "time" : {
          "start" : 1727921089666,
          "stop" : 1727921090580,
          "duration" : 914
        }
      }, {
        "uid" : "85e7599560451848",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/85e7599560451848",
        "status" : "passed",
        "time" : {
          "start" : 1727834387735,
          "stop" : 1727834388579,
          "duration" : 844
        }
      }, {
        "uid" : "be6f3016a98345a2",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/be6f3016a98345a2",
        "status" : "passed",
        "time" : {
          "start" : 1727748542447,
          "stop" : 1727748543310,
          "duration" : 863
        }
      }, {
        "uid" : "45e00b6ab8b44861",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/45e00b6ab8b44861",
        "status" : "passed",
        "time" : {
          "start" : 1727661792124,
          "stop" : 1727661792972,
          "duration" : 848
        }
      }, {
        "uid" : "290791d7a5dc28b",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/290791d7a5dc28b",
        "status" : "passed",
        "time" : {
          "start" : 1727575723188,
          "stop" : 1727575724038,
          "duration" : 850
        }
      }, {
        "uid" : "d4dbe3a808d81701",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/d4dbe3a808d81701",
        "status" : "passed",
        "time" : {
          "start" : 1727489048749,
          "stop" : 1727489049584,
          "duration" : 835
        }
      }, {
        "uid" : "9f968d80c32fe6c5",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/9f968d80c32fe6c5",
        "status" : "passed",
        "time" : {
          "start" : 1727402757700,
          "stop" : 1727402758608,
          "duration" : 908
        }
      }, {
        "uid" : "8c9413f7b6d9bcc5",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/8c9413f7b6d9bcc5",
        "status" : "passed",
        "time" : {
          "start" : 1727316315395,
          "stop" : 1727316316286,
          "duration" : 891
        }
      }, {
        "uid" : "c1492e8993b1049c",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/c1492e8993b1049c",
        "status" : "passed",
        "time" : {
          "start" : 1727229914861,
          "stop" : 1727229915711,
          "duration" : 850
        }
      }, {
        "uid" : "f8c19e0e7b077912",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/f8c19e0e7b077912",
        "status" : "passed",
        "time" : {
          "start" : 1727143240966,
          "stop" : 1727143241810,
          "duration" : 844
        }
      }, {
        "uid" : "9b42b52ea97379e9",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/9b42b52ea97379e9",
        "status" : "passed",
        "time" : {
          "start" : 1727056670408,
          "stop" : 1727056671225,
          "duration" : 817
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "1f05c25385384319.json",
  "parameterValues" : [ ]
}