{
  "uid" : "4901c796c806b990",
  "name" : "Verify that the email link calls an email client",
  "fullName" : "tests.contacts_page_test.TestContactsPageLinks#test_cp_03_03_verify_email_link_calls_an_email_client",
  "historyId" : "439979364f81ff50b7b18242ebace4b6",
  "time" : {
    "start" : 1728784112844,
    "stop" : 1728784112844,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55851c4ae02a <unknown>\n#1 0x55851c1945e0 <unknown>\n#2 0x55851c18c7eb <unknown>\n#3 0x55851c17ca09 <unknown>\n#4 0x55851c17e744 <unknown>\n#5 0x55851c17ccbd <unknown>\n#6 0x55851c17c52f <unknown>\n#7 0x55851c17c422 <unknown>\n#8 0x55851c17a493 <unknown>\n#9 0x55851c17aada <unknown>\n#10 0x55851c196f41 <unknown>\n#11 0x55851c2288c5 <unknown>\n#12 0x55851c208b22 <unknown>\n#13 0x55851c227d7d <unknown>\n#14 0x55851c2088c3 <unknown>\n#15 0x55851c1d66b3 <unknown>\n#16 0x55851c1d768e <unknown>\n#17 0x55851c478a2b <unknown>\n#18 0x55851c47c9b1 <unknown>\n#19 0x55851c465225 <unknown>\n#20 0x55851c47d532 <unknown>\n#21 0x55851c44a38f <unknown>\n#22 0x55851c49cf28 <unknown>\n#23 0x55851c49d0f3 <unknown>\n#24 0x55851c4ace7c <unknown>\n#25 0x7f1258694ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"ba29570095ee66c008ad22a594f9a3fe\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7faf1f7eb650>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55851c49d0f3 \\\\u003Cunknown>\\\\n#24 0x55851c4ace7c \\\\u003Cunknown>\\\\n#25 0x7f1258694ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55851c4ae02a <unknown>\nE       #1 0x55851c1945e0 <unknown>\nE       #2 0x55851c18c7eb <unknown>\nE       #3 0x55851c17ca09 <unknown>\nE       #4 0x55851c17e744 <unknown>\nE       #5 0x55851c17ccbd <unknown>\nE       #6 0x55851c17c52f <unknown>\nE       #7 0x55851c17c422 <unknown>\nE       #8 0x55851c17a493 <unknown>\nE       #9 0x55851c17aada <unknown>\nE       #10 0x55851c196f41 <unknown>\nE       #11 0x55851c2288c5 <unknown>\nE       #12 0x55851c208b22 <unknown>\nE       #13 0x55851c227d7d <unknown>\nE       #14 0x55851c2088c3 <unknown>\nE       #15 0x55851c1d66b3 <unknown>\nE       #16 0x55851c1d768e <unknown>\nE       #17 0x55851c478a2b <unknown>\nE       #18 0x55851c47c9b1 <unknown>\nE       #19 0x55851c465225 <unknown>\nE       #20 0x55851c47d532 <unknown>\nE       #21 0x55851c44a38f <unknown>\nE       #22 0x55851c49cf28 <unknown>\nE       #23 0x55851c49d0f3 <unknown>\nE       #24 0x55851c4ace7c <unknown>\nE       #25 0x7f1258694ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728784074935,
      "stop" : 1728784074936,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728784113608,
      "stop" : 1728784114034,
      "duration" : 426
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55851c4ae02a <unknown>\n#1 0x55851c1945e0 <unknown>\n#2 0x55851c18c7eb <unknown>\n#3 0x55851c17ca09 <unknown>\n#4 0x55851c17e744 <unknown>\n#5 0x55851c17ccbd <unknown>\n#6 0x55851c17c52f <unknown>\n#7 0x55851c17c422 <unknown>\n#8 0x55851c17a493 <unknown>\n#9 0x55851c17aada <unknown>\n#10 0x55851c196f41 <unknown>\n#11 0x55851c2288c5 <unknown>\n#12 0x55851c208b22 <unknown>\n#13 0x55851c227d7d <unknown>\n#14 0x55851c2088c3 <unknown>\n#15 0x55851c1d66b3 <unknown>\n#16 0x55851c1d768e <unknown>\n#17 0x55851c478a2b <unknown>\n#18 0x55851c47c9b1 <unknown>\n#19 0x55851c465225 <unknown>\n#20 0x55851c47d532 <unknown>\n#21 0x55851c44a38f <unknown>\n#22 0x55851c49cf28 <unknown>\n#23 0x55851c49d0f3 <unknown>\n#24 0x55851c4ace7c <unknown>\n#25 0x7f1258694ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728784113608,
        "stop" : 1728784114034,
        "duration" : 426
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55851c4ae02a <unknown>\n#1 0x55851c1945e0 <unknown>\n#2 0x55851c18c7eb <unknown>\n#3 0x55851c17ca09 <unknown>\n#4 0x55851c17e744 <unknown>\n#5 0x55851c17ccbd <unknown>\n#6 0x55851c17c52f <unknown>\n#7 0x55851c17c422 <unknown>\n#8 0x55851c17a493 <unknown>\n#9 0x55851c17aada <unknown>\n#10 0x55851c196f41 <unknown>\n#11 0x55851c2288c5 <unknown>\n#12 0x55851c208b22 <unknown>\n#13 0x55851c227d7d <unknown>\n#14 0x55851c2088c3 <unknown>\n#15 0x55851c1d66b3 <unknown>\n#16 0x55851c1d768e <unknown>\n#17 0x55851c478a2b <unknown>\n#18 0x55851c47c9b1 <unknown>\n#19 0x55851c465225 <unknown>\n#20 0x55851c47d532 <unknown>\n#21 0x55851c44a38f <unknown>\n#22 0x55851c49cf28 <unknown>\n#23 0x55851c49d0f3 <unknown>\n#24 0x55851c4ace7c <unknown>\n#25 0x7f1258694ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"ba29570095ee66c008ad22a594f9a3fe\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728784112845,
      "stop" : 1728784113608,
      "duration" : 763
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728784114066,
      "stop" : 1728784114128,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "The Contacts Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "contacts_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestContactsPage"
  }, {
    "name" : "host",
    "value" : "fv-az891-551"
  }, {
    "name" : "thread",
    "value" : "2367-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.contacts_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 3,
        "skipped" : 0,
        "passed" : 28,
        "unknown" : 0,
        "total" : 31
      },
      "items" : [ {
        "uid" : "af56a7c4350715f6",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/60//#testresult/af56a7c4350715f6",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5613b5b8302a <unknown>\n#1 0x5613b58695e0 <unknown>\n#2 0x5613b58617eb <unknown>\n#3 0x5613b5851a09 <unknown>\n#4 0x5613b5853744 <unknown>\n#5 0x5613b5851cbd <unknown>\n#6 0x5613b585152f <unknown>\n#7 0x5613b5851422 <unknown>\n#8 0x5613b584f493 <unknown>\n#9 0x5613b584fada <unknown>\n#10 0x5613b586bf41 <unknown>\n#11 0x5613b58fd8c5 <unknown>\n#12 0x5613b58ddb22 <unknown>\n#13 0x5613b58fcd7d <unknown>\n#14 0x5613b58dd8c3 <unknown>\n#15 0x5613b58ab6b3 <unknown>\n#16 0x5613b58ac68e <unknown>\n#17 0x5613b5b4da2b <unknown>\n#18 0x5613b5b519b1 <unknown>\n#19 0x5613b5b3a225 <unknown>\n#20 0x5613b5b52532 <unknown>\n#21 0x5613b5b1f38f <unknown>\n#22 0x5613b5b71f28 <unknown>\n#23 0x5613b5b720f3 <unknown>\n#24 0x5613b5b81e7c <unknown>\n#25 0x7f303bc94ac3 <unknown>",
        "time" : {
          "start" : 1728697226801,
          "stop" : 1728697226801,
          "duration" : 0
        }
      }, {
        "uid" : "dd23c8beb2b5e53c",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/dd23c8beb2b5e53c",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x563aa0a4a02a <unknown>\n#1 0x563aa07305e0 <unknown>\n#2 0x563aa07287eb <unknown>\n#3 0x563aa0718a09 <unknown>\n#4 0x563aa071a744 <unknown>\n#5 0x563aa0718cbd <unknown>\n#6 0x563aa071852f <unknown>\n#7 0x563aa0718422 <unknown>\n#8 0x563aa0716493 <unknown>\n#9 0x563aa0716ada <unknown>\n#10 0x563aa0732f41 <unknown>\n#11 0x563aa07c48c5 <unknown>\n#12 0x563aa07a4b22 <unknown>\n#13 0x563aa07c3d7d <unknown>\n#14 0x563aa07a48c3 <unknown>\n#15 0x563aa07726b3 <unknown>\n#16 0x563aa077368e <unknown>\n#17 0x563aa0a14a2b <unknown>\n#18 0x563aa0a189b1 <unknown>\n#19 0x563aa0a01225 <unknown>\n#20 0x563aa0a19532 <unknown>\n#21 0x563aa09e638f <unknown>\n#22 0x563aa0a38f28 <unknown>\n#23 0x563aa0a390f3 <unknown>\n#24 0x563aa0a48e7c <unknown>\n#25 0x7f1b2ca94ac3 <unknown>",
        "time" : {
          "start" : 1728610918145,
          "stop" : 1728610918145,
          "duration" : 0
        }
      }, {
        "uid" : "ba0412a163891b3c",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/ba0412a163891b3c",
        "status" : "passed",
        "time" : {
          "start" : 1728524591142,
          "stop" : 1728524591230,
          "duration" : 88
        }
      }, {
        "uid" : "5120572fab97d32f",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/5120572fab97d32f",
        "status" : "passed",
        "time" : {
          "start" : 1728438163351,
          "stop" : 1728438163441,
          "duration" : 90
        }
      }, {
        "uid" : "c899bf25aa10d35",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/c899bf25aa10d35",
        "status" : "passed",
        "time" : {
          "start" : 1728351821528,
          "stop" : 1728351821619,
          "duration" : 91
        }
      }, {
        "uid" : "d7921a1789946497",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/d7921a1789946497",
        "status" : "passed",
        "time" : {
          "start" : 1728265607494,
          "stop" : 1728265607584,
          "duration" : 90
        }
      }, {
        "uid" : "3971bb3984afeb2",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/3971bb3984afeb2",
        "status" : "passed",
        "time" : {
          "start" : 1728179379423,
          "stop" : 1728179379513,
          "duration" : 90
        }
      }, {
        "uid" : "c6fb4180c019d419",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/c6fb4180c019d419",
        "status" : "passed",
        "time" : {
          "start" : 1728092543529,
          "stop" : 1728092543615,
          "duration" : 86
        }
      }, {
        "uid" : "3afc1c305d83ece0",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/3afc1c305d83ece0",
        "status" : "passed",
        "time" : {
          "start" : 1728006249353,
          "stop" : 1728006249445,
          "duration" : 92
        }
      }, {
        "uid" : "20f8147e9013a47b",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/20f8147e9013a47b",
        "status" : "passed",
        "time" : {
          "start" : 1727919837280,
          "stop" : 1727919837375,
          "duration" : 95
        }
      }, {
        "uid" : "a104d1ffc0ab570d",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/a104d1ffc0ab570d",
        "status" : "passed",
        "time" : {
          "start" : 1727833387638,
          "stop" : 1727833387729,
          "duration" : 91
        }
      }, {
        "uid" : "8c4fde9847f0bf4c",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/8c4fde9847f0bf4c",
        "status" : "passed",
        "time" : {
          "start" : 1727747523860,
          "stop" : 1727747523950,
          "duration" : 90
        }
      }, {
        "uid" : "56cc946ce41d0bf5",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/56cc946ce41d0bf5",
        "status" : "passed",
        "time" : {
          "start" : 1727660805157,
          "stop" : 1727660805248,
          "duration" : 91
        }
      }, {
        "uid" : "3db4e654f4f9ddf8",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/3db4e654f4f9ddf8",
        "status" : "passed",
        "time" : {
          "start" : 1727574608428,
          "stop" : 1727574608518,
          "duration" : 90
        }
      }, {
        "uid" : "802065bd10c9818a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/802065bd10c9818a",
        "status" : "passed",
        "time" : {
          "start" : 1727487859383,
          "stop" : 1727487859473,
          "duration" : 90
        }
      }, {
        "uid" : "a1d6f450528d8442",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/a1d6f450528d8442",
        "status" : "passed",
        "time" : {
          "start" : 1727401431290,
          "stop" : 1727401431381,
          "duration" : 91
        }
      }, {
        "uid" : "8e443ec12960c8d3",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/8e443ec12960c8d3",
        "status" : "passed",
        "time" : {
          "start" : 1727314978229,
          "stop" : 1727314978316,
          "duration" : 87
        }
      }, {
        "uid" : "df11abf3597b0e52",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/df11abf3597b0e52",
        "status" : "passed",
        "time" : {
          "start" : 1727228669682,
          "stop" : 1727228669771,
          "duration" : 89
        }
      }, {
        "uid" : "734ef4b43e2d8e99",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/734ef4b43e2d8e99",
        "status" : "passed",
        "time" : {
          "start" : 1727142231091,
          "stop" : 1727142231183,
          "duration" : 92
        }
      }, {
        "uid" : "33d97cf03b2bcc49",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/33d97cf03b2bcc49",
        "status" : "passed",
        "time" : {
          "start" : 1727055785473,
          "stop" : 1727055785559,
          "duration" : 86
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "4901c796c806b990.json",
  "parameterValues" : [ ]
}