{
  "uid" : "4abbe6511aa6d63",
  "name" : "Select a random card from \"Похожие фразы\" group and compare UI vs BACKEND data.",
  "fullName" : "tests.test_speech_exercises_ru.TestCardsRU#test_random_cards_in_similar_phrases_ru",
  "historyId" : "5e981df7bf46eebe64ca49edd6dd6d63",
  "time" : {
    "start" : 1728784239625,
    "stop" : 1728784239625,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x563353da302a <unknown>\n#1 0x563353a895e0 <unknown>\n#2 0x563353a817eb <unknown>\n#3 0x563353a71a09 <unknown>\n#4 0x563353a73744 <unknown>\n#5 0x563353a71cbd <unknown>\n#6 0x563353a7152f <unknown>\n#7 0x563353a71422 <unknown>\n#8 0x563353a6f493 <unknown>\n#9 0x563353a6fada <unknown>\n#10 0x563353a8bf41 <unknown>\n#11 0x563353b1d8c5 <unknown>\n#12 0x563353afdb22 <unknown>\n#13 0x563353b1cd7d <unknown>\n#14 0x563353afd8c3 <unknown>\n#15 0x563353acb6b3 <unknown>\n#16 0x563353acc68e <unknown>\n#17 0x563353d6da2b <unknown>\n#18 0x563353d719b1 <unknown>\n#19 0x563353d5a225 <unknown>\n#20 0x563353d72532 <unknown>\n#21 0x563353d3f38f <unknown>\n#22 0x563353d91f28 <unknown>\n#23 0x563353d920f3 <unknown>\n#24 0x563353da1e7c <unknown>\n#25 0x7fb8fa094ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"3d09763e7ea9abc3a176bf7ba3a6759b\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7faf1f713260>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x563353d920f3 \\\\u003Cunknown>\\\\n#24 0x563353da1e7c \\\\u003Cunknown>\\\\n#25 0x7fb8fa094ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x563353da302a <unknown>\nE       #1 0x563353a895e0 <unknown>\nE       #2 0x563353a817eb <unknown>\nE       #3 0x563353a71a09 <unknown>\nE       #4 0x563353a73744 <unknown>\nE       #5 0x563353a71cbd <unknown>\nE       #6 0x563353a7152f <unknown>\nE       #7 0x563353a71422 <unknown>\nE       #8 0x563353a6f493 <unknown>\nE       #9 0x563353a6fada <unknown>\nE       #10 0x563353a8bf41 <unknown>\nE       #11 0x563353b1d8c5 <unknown>\nE       #12 0x563353afdb22 <unknown>\nE       #13 0x563353b1cd7d <unknown>\nE       #14 0x563353afd8c3 <unknown>\nE       #15 0x563353acb6b3 <unknown>\nE       #16 0x563353acc68e <unknown>\nE       #17 0x563353d6da2b <unknown>\nE       #18 0x563353d719b1 <unknown>\nE       #19 0x563353d5a225 <unknown>\nE       #20 0x563353d72532 <unknown>\nE       #21 0x563353d3f38f <unknown>\nE       #22 0x563353d91f28 <unknown>\nE       #23 0x563353d920f3 <unknown>\nE       #24 0x563353da1e7c <unknown>\nE       #25 0x7fb8fa094ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728784074935,
      "stop" : 1728784074936,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728784240397,
      "stop" : 1728784240828,
      "duration" : 431
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x563353da302a <unknown>\n#1 0x563353a895e0 <unknown>\n#2 0x563353a817eb <unknown>\n#3 0x563353a71a09 <unknown>\n#4 0x563353a73744 <unknown>\n#5 0x563353a71cbd <unknown>\n#6 0x563353a7152f <unknown>\n#7 0x563353a71422 <unknown>\n#8 0x563353a6f493 <unknown>\n#9 0x563353a6fada <unknown>\n#10 0x563353a8bf41 <unknown>\n#11 0x563353b1d8c5 <unknown>\n#12 0x563353afdb22 <unknown>\n#13 0x563353b1cd7d <unknown>\n#14 0x563353afd8c3 <unknown>\n#15 0x563353acb6b3 <unknown>\n#16 0x563353acc68e <unknown>\n#17 0x563353d6da2b <unknown>\n#18 0x563353d719b1 <unknown>\n#19 0x563353d5a225 <unknown>\n#20 0x563353d72532 <unknown>\n#21 0x563353d3f38f <unknown>\n#22 0x563353d91f28 <unknown>\n#23 0x563353d920f3 <unknown>\n#24 0x563353da1e7c <unknown>\n#25 0x7fb8fa094ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728784240397,
        "stop" : 1728784240827,
        "duration" : 430
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x563353da302a <unknown>\n#1 0x563353a895e0 <unknown>\n#2 0x563353a817eb <unknown>\n#3 0x563353a71a09 <unknown>\n#4 0x563353a73744 <unknown>\n#5 0x563353a71cbd <unknown>\n#6 0x563353a7152f <unknown>\n#7 0x563353a71422 <unknown>\n#8 0x563353a6f493 <unknown>\n#9 0x563353a6fada <unknown>\n#10 0x563353a8bf41 <unknown>\n#11 0x563353b1d8c5 <unknown>\n#12 0x563353afdb22 <unknown>\n#13 0x563353b1cd7d <unknown>\n#14 0x563353afd8c3 <unknown>\n#15 0x563353acb6b3 <unknown>\n#16 0x563353acc68e <unknown>\n#17 0x563353d6da2b <unknown>\n#18 0x563353d719b1 <unknown>\n#19 0x563353d5a225 <unknown>\n#20 0x563353d72532 <unknown>\n#21 0x563353d3f38f <unknown>\n#22 0x563353d91f28 <unknown>\n#23 0x563353d920f3 <unknown>\n#24 0x563353da1e7c <unknown>\n#25 0x7fb8fa094ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"3d09763e7ea9abc3a176bf7ba3a6759b\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728784239625,
      "stop" : 1728784240397,
      "duration" : 772
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728784240859,
      "stop" : 1728784240921,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Speech exercises."
  }, {
    "name" : "suite",
    "value" : "Речевые упражнения."
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "subSuite",
    "value" : "TestCardsRU"
  }, {
    "name" : "host",
    "value" : "fv-az891-551"
  }, {
    "name" : "thread",
    "value" : "2367-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_speech_exercises_ru"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 9,
        "passed" : 52,
        "unknown" : 0,
        "total" : 61
      },
      "items" : [ {
        "uid" : "7de2e49e0a3decfd",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/60//#testresult/7de2e49e0a3decfd",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55c3d633c02a <unknown>\n#1 0x55c3d60225e0 <unknown>\n#2 0x55c3d601a7eb <unknown>\n#3 0x55c3d600aa09 <unknown>\n#4 0x55c3d600c744 <unknown>\n#5 0x55c3d600acbd <unknown>\n#6 0x55c3d600a52f <unknown>\n#7 0x55c3d600a422 <unknown>\n#8 0x55c3d6008493 <unknown>\n#9 0x55c3d6008ada <unknown>\n#10 0x55c3d6024f41 <unknown>\n#11 0x55c3d60b68c5 <unknown>\n#12 0x55c3d6096b22 <unknown>\n#13 0x55c3d60b5d7d <unknown>\n#14 0x55c3d60968c3 <unknown>\n#15 0x55c3d60646b3 <unknown>\n#16 0x55c3d606568e <unknown>\n#17 0x55c3d6306a2b <unknown>\n#18 0x55c3d630a9b1 <unknown>\n#19 0x55c3d62f3225 <unknown>\n#20 0x55c3d630b532 <unknown>\n#21 0x55c3d62d838f <unknown>\n#22 0x55c3d632af28 <unknown>\n#23 0x55c3d632b0f3 <unknown>\n#24 0x55c3d633ae7c <unknown>\n#25 0x7fadd8c94ac3 <unknown>",
        "time" : {
          "start" : 1728697353612,
          "stop" : 1728697353612,
          "duration" : 0
        }
      }, {
        "uid" : "75947ad31e56e81a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/75947ad31e56e81a",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55ce99ead02a <unknown>\n#1 0x55ce99b935e0 <unknown>\n#2 0x55ce99b8b7eb <unknown>\n#3 0x55ce99b7ba09 <unknown>\n#4 0x55ce99b7d744 <unknown>\n#5 0x55ce99b7bcbd <unknown>\n#6 0x55ce99b7b52f <unknown>\n#7 0x55ce99b7b422 <unknown>\n#8 0x55ce99b79493 <unknown>\n#9 0x55ce99b79ada <unknown>\n#10 0x55ce99b95f41 <unknown>\n#11 0x55ce99c278c5 <unknown>\n#12 0x55ce99c07b22 <unknown>\n#13 0x55ce99c26d7d <unknown>\n#14 0x55ce99c078c3 <unknown>\n#15 0x55ce99bd56b3 <unknown>\n#16 0x55ce99bd668e <unknown>\n#17 0x55ce99e77a2b <unknown>\n#18 0x55ce99e7b9b1 <unknown>\n#19 0x55ce99e64225 <unknown>\n#20 0x55ce99e7c532 <unknown>\n#21 0x55ce99e4938f <unknown>\n#22 0x55ce99e9bf28 <unknown>\n#23 0x55ce99e9c0f3 <unknown>\n#24 0x55ce99eabe7c <unknown>\n#25 0x7fdfa9c94ac3 <unknown>",
        "time" : {
          "start" : 1728611044826,
          "stop" : 1728611044826,
          "duration" : 0
        }
      }, {
        "uid" : "88612b2e9d186186",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/88612b2e9d186186",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728525164544,
          "stop" : 1728525174915,
          "duration" : 10371
        }
      }, {
        "uid" : "88d360dba2c3f91d",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/88d360dba2c3f91d",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728438833700,
          "stop" : 1728438843664,
          "duration" : 9964
        }
      }, {
        "uid" : "42a859b43d5b0a7a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/42a859b43d5b0a7a",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728352433742,
          "stop" : 1728352444455,
          "duration" : 10713
        }
      }, {
        "uid" : "d90f76f85eca3658",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/d90f76f85eca3658",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728267175094,
          "stop" : 1728267175094,
          "duration" : 0
        }
      }, {
        "uid" : "e03a7fdcb42dc7a2",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/e03a7fdcb42dc7a2",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728179972348,
          "stop" : 1728179983394,
          "duration" : 11046
        }
      }, {
        "uid" : "fced8e12bf6765db",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/fced8e12bf6765db",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728093241845,
          "stop" : 1728093253728,
          "duration" : 11883
        }
      }, {
        "uid" : "1ae46d01cc9a9e41",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/1ae46d01cc9a9e41",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728006946421,
          "stop" : 1728006958217,
          "duration" : 11796
        }
      }, {
        "uid" : "49ec0f95c07fc661",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/49ec0f95c07fc661",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727920700600,
          "stop" : 1727920713265,
          "duration" : 12665
        }
      }, {
        "uid" : "c45fe297f581f45e",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/c45fe297f581f45e",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//button[@title=\"Распознавание похожих фраз\"]')\nStacktrace:\n#0 0x56413ed0013a <unknown>\n#1 0x56413e9e65e0 <unknown>\n#2 0x56413ea35be8 <unknown>\n#3 0x56413ea35e81 <unknown>\n#4 0x56413ea7c8c4 <unknown>\n#5 0x56413ea5ab4d <unknown>\n#6 0x56413ea79d7d <unknown>\n#7 0x56413ea5a8c3 <unknown>\n#8 0x56413ea286b3 <unknown>\n#9 0x56413ea2968e <unknown>\n#10 0x56413eccab3b <unknown>\n#11 0x56413ecceac1 <unknown>\n#12 0x56413ecb7335 <unknown>\n#13 0x56413eccf642 <unknown>\n#14 0x56413ec9c49f <unknown>\n#15 0x56413ecef038 <unknown>\n#16 0x56413ecef203 <unknown>\n#17 0x56413ecfef8c <unknown>\n#18 0x7f13f7a94ac3 <unknown>",
        "time" : {
          "start" : 1727834053423,
          "stop" : 1727834074622,
          "duration" : 21199
        }
      }, {
        "uid" : "45fc4d19d9b3268",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/45fc4d19d9b3268",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727748199952,
          "stop" : 1727748211713,
          "duration" : 11761
        }
      }, {
        "uid" : "26d65507768a1791",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/26d65507768a1791",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727661476939,
          "stop" : 1727661490219,
          "duration" : 13280
        }
      }, {
        "uid" : "839d9b9d74b48935",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/839d9b9d74b48935",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Url: https://brainup.site/groups/2/series/2/subgroup/62/exercise/1457 has not been changed!!!",
        "time" : {
          "start" : 1727575326590,
          "stop" : 1727575369281,
          "duration" : 42691
        }
      }, {
        "uid" : "80fe962b3f30c118",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/80fe962b3f30c118",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727488579746,
          "stop" : 1727488591247,
          "duration" : 11501
        }
      }, {
        "uid" : "4a579b680ca46768",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/4a579b680ca46768",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727402330259,
          "stop" : 1727402346482,
          "duration" : 16223
        }
      }, {
        "uid" : "d124cfdec7d8c3ac",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/d124cfdec7d8c3ac",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727315809370,
          "stop" : 1727315868926,
          "duration" : 59556
        }
      }, {
        "uid" : "f2e0cb9e50bc15b1",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/f2e0cb9e50bc15b1",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727229472354,
          "stop" : 1727229500384,
          "duration" : 28030
        }
      }, {
        "uid" : "e88981f826f514c9",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/e88981f826f514c9",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727142949513,
          "stop" : 1727142959679,
          "duration" : 10166
        }
      }, {
        "uid" : "8f06cecd9823655f",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/8f06cecd9823655f",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727056344166,
          "stop" : 1727056353877,
          "duration" : 9711
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail" ]
  },
  "source" : "4abbe6511aa6d63.json",
  "parameterValues" : [ ]
}