{
  "uid" : "678bbd11279fa1ca",
  "name" : "Verify redirection to contributors page not authorized user.",
  "fullName" : "tests.description_page_test.TestDescriptionPage#test_dp_07_verify_redirection_to_contributors_page",
  "historyId" : "85f2b35427a7bcbc7a8256ab71746c1d",
  "time" : {
    "start" : 1728784137405,
    "stop" : 1728784137405,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x558197bfe02a <unknown>\n#1 0x5581978e45e0 <unknown>\n#2 0x5581978dc7eb <unknown>\n#3 0x5581978cca09 <unknown>\n#4 0x5581978ce744 <unknown>\n#5 0x5581978cccbd <unknown>\n#6 0x5581978cc52f <unknown>\n#7 0x5581978cc422 <unknown>\n#8 0x5581978ca493 <unknown>\n#9 0x5581978caada <unknown>\n#10 0x5581978e6f41 <unknown>\n#11 0x5581979788c5 <unknown>\n#12 0x558197958b22 <unknown>\n#13 0x558197977d7d <unknown>\n#14 0x5581979588c3 <unknown>\n#15 0x5581979266b3 <unknown>\n#16 0x55819792768e <unknown>\n#17 0x558197bc8a2b <unknown>\n#18 0x558197bcc9b1 <unknown>\n#19 0x558197bb5225 <unknown>\n#20 0x558197bcd532 <unknown>\n#21 0x558197b9a38f <unknown>\n#22 0x558197becf28 <unknown>\n#23 0x558197bed0f3 <unknown>\n#24 0x558197bfce7c <unknown>\n#25 0x7fdf51094ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f4ee0fe2860a1691799cec2a2423c38e\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7faf1f7dd6a0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x558197bed0f3 \\\\u003Cunknown>\\\\n#24 0x558197bfce7c \\\\u003Cunknown>\\\\n#25 0x7fdf51094ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x558197bfe02a <unknown>\nE       #1 0x5581978e45e0 <unknown>\nE       #2 0x5581978dc7eb <unknown>\nE       #3 0x5581978cca09 <unknown>\nE       #4 0x5581978ce744 <unknown>\nE       #5 0x5581978cccbd <unknown>\nE       #6 0x5581978cc52f <unknown>\nE       #7 0x5581978cc422 <unknown>\nE       #8 0x5581978ca493 <unknown>\nE       #9 0x5581978caada <unknown>\nE       #10 0x5581978e6f41 <unknown>\nE       #11 0x5581979788c5 <unknown>\nE       #12 0x558197958b22 <unknown>\nE       #13 0x558197977d7d <unknown>\nE       #14 0x5581979588c3 <unknown>\nE       #15 0x5581979266b3 <unknown>\nE       #16 0x55819792768e <unknown>\nE       #17 0x558197bc8a2b <unknown>\nE       #18 0x558197bcc9b1 <unknown>\nE       #19 0x558197bb5225 <unknown>\nE       #20 0x558197bcd532 <unknown>\nE       #21 0x558197b9a38f <unknown>\nE       #22 0x558197becf28 <unknown>\nE       #23 0x558197bed0f3 <unknown>\nE       #24 0x558197bfce7c <unknown>\nE       #25 0x7fdf51094ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728784074935,
      "stop" : 1728784074936,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728784137405,
      "stop" : 1728784138176,
      "duration" : 771
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728784138176,
      "stop" : 1728784138600,
      "duration" : 424
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x558197bfe02a <unknown>\n#1 0x5581978e45e0 <unknown>\n#2 0x5581978dc7eb <unknown>\n#3 0x5581978cca09 <unknown>\n#4 0x5581978ce744 <unknown>\n#5 0x5581978cccbd <unknown>\n#6 0x5581978cc52f <unknown>\n#7 0x5581978cc422 <unknown>\n#8 0x5581978ca493 <unknown>\n#9 0x5581978caada <unknown>\n#10 0x5581978e6f41 <unknown>\n#11 0x5581979788c5 <unknown>\n#12 0x558197958b22 <unknown>\n#13 0x558197977d7d <unknown>\n#14 0x5581979588c3 <unknown>\n#15 0x5581979266b3 <unknown>\n#16 0x55819792768e <unknown>\n#17 0x558197bc8a2b <unknown>\n#18 0x558197bcc9b1 <unknown>\n#19 0x558197bb5225 <unknown>\n#20 0x558197bcd532 <unknown>\n#21 0x558197b9a38f <unknown>\n#22 0x558197becf28 <unknown>\n#23 0x558197bed0f3 <unknown>\n#24 0x558197bfce7c <unknown>\n#25 0x7fdf51094ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728784138176,
        "stop" : 1728784138599,
        "duration" : 423
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x558197bfe02a <unknown>\n#1 0x5581978e45e0 <unknown>\n#2 0x5581978dc7eb <unknown>\n#3 0x5581978cca09 <unknown>\n#4 0x5581978ce744 <unknown>\n#5 0x5581978cccbd <unknown>\n#6 0x5581978cc52f <unknown>\n#7 0x5581978cc422 <unknown>\n#8 0x5581978ca493 <unknown>\n#9 0x5581978caada <unknown>\n#10 0x5581978e6f41 <unknown>\n#11 0x5581979788c5 <unknown>\n#12 0x558197958b22 <unknown>\n#13 0x558197977d7d <unknown>\n#14 0x5581979588c3 <unknown>\n#15 0x5581979266b3 <unknown>\n#16 0x55819792768e <unknown>\n#17 0x558197bc8a2b <unknown>\n#18 0x558197bcc9b1 <unknown>\n#19 0x558197bb5225 <unknown>\n#20 0x558197bcd532 <unknown>\n#21 0x558197b9a38f <unknown>\n#22 0x558197becf28 <unknown>\n#23 0x558197bed0f3 <unknown>\n#24 0x558197bfce7c <unknown>\n#25 0x7fdf51094ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"f4ee0fe2860a1691799cec2a2423c38e\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728784138631,
      "stop" : 1728784138693,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Description Page."
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "description_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestDescriptionPage"
  }, {
    "name" : "host",
    "value" : "fv-az891-551"
  }, {
    "name" : "thread",
    "value" : "2367-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.description_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 57,
        "unknown" : 0,
        "total" : 61
      },
      "items" : [ {
        "uid" : "472f996c1cd00629",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/60//#testresult/472f996c1cd00629",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x557f4e51c02a <unknown>\n#1 0x557f4e2025e0 <unknown>\n#2 0x557f4e1fa7eb <unknown>\n#3 0x557f4e1eaa09 <unknown>\n#4 0x557f4e1ec744 <unknown>\n#5 0x557f4e1eacbd <unknown>\n#6 0x557f4e1ea52f <unknown>\n#7 0x557f4e1ea422 <unknown>\n#8 0x557f4e1e8493 <unknown>\n#9 0x557f4e1e8ada <unknown>\n#10 0x557f4e204f41 <unknown>\n#11 0x557f4e2968c5 <unknown>\n#12 0x557f4e276b22 <unknown>\n#13 0x557f4e295d7d <unknown>\n#14 0x557f4e2768c3 <unknown>\n#15 0x557f4e2446b3 <unknown>\n#16 0x557f4e24568e <unknown>\n#17 0x557f4e4e6a2b <unknown>\n#18 0x557f4e4ea9b1 <unknown>\n#19 0x557f4e4d3225 <unknown>\n#20 0x557f4e4eb532 <unknown>\n#21 0x557f4e4b838f <unknown>\n#22 0x557f4e50af28 <unknown>\n#23 0x557f4e50b0f3 <unknown>\n#24 0x557f4e51ae7c <unknown>\n#25 0x7fdad2294ac3 <unknown>",
        "time" : {
          "start" : 1728697251381,
          "stop" : 1728697251381,
          "duration" : 0
        }
      }, {
        "uid" : "28d34d6989b9bb0b",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/28d34d6989b9bb0b",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55ce835a602a <unknown>\n#1 0x55ce8328c5e0 <unknown>\n#2 0x55ce832847eb <unknown>\n#3 0x55ce83274a09 <unknown>\n#4 0x55ce83276744 <unknown>\n#5 0x55ce83274cbd <unknown>\n#6 0x55ce8327452f <unknown>\n#7 0x55ce83274422 <unknown>\n#8 0x55ce83272493 <unknown>\n#9 0x55ce83272ada <unknown>\n#10 0x55ce8328ef41 <unknown>\n#11 0x55ce833208c5 <unknown>\n#12 0x55ce83300b22 <unknown>\n#13 0x55ce8331fd7d <unknown>\n#14 0x55ce833008c3 <unknown>\n#15 0x55ce832ce6b3 <unknown>\n#16 0x55ce832cf68e <unknown>\n#17 0x55ce83570a2b <unknown>\n#18 0x55ce835749b1 <unknown>\n#19 0x55ce8355d225 <unknown>\n#20 0x55ce83575532 <unknown>\n#21 0x55ce8354238f <unknown>\n#22 0x55ce83594f28 <unknown>\n#23 0x55ce835950f3 <unknown>\n#24 0x55ce835a4e7c <unknown>\n#25 0x7f7382a94ac3 <unknown>",
        "time" : {
          "start" : 1728610942736,
          "stop" : 1728610942736,
          "duration" : 0
        }
      }, {
        "uid" : "b30c5646f0de6b86",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/b30c5646f0de6b86",
        "status" : "passed",
        "time" : {
          "start" : 1728524672149,
          "stop" : 1728524672800,
          "duration" : 651
        }
      }, {
        "uid" : "6427ef0c85a279e4",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/6427ef0c85a279e4",
        "status" : "passed",
        "time" : {
          "start" : 1728438243427,
          "stop" : 1728438244073,
          "duration" : 646
        }
      }, {
        "uid" : "be2e134474e80e4f",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/be2e134474e80e4f",
        "status" : "passed",
        "time" : {
          "start" : 1728351910764,
          "stop" : 1728351911431,
          "duration" : 667
        }
      }, {
        "uid" : "99fcef2fb9698f4a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/99fcef2fb9698f4a",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/contributors",
        "time" : {
          "start" : 1728265929599,
          "stop" : 1728265970053,
          "duration" : 40454
        }
      }, {
        "uid" : "42d6f157b38025b0",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/42d6f157b38025b0",
        "status" : "passed",
        "time" : {
          "start" : 1728179464509,
          "stop" : 1728179465156,
          "duration" : 647
        }
      }, {
        "uid" : "2a7036ef414c3d6e",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/2a7036ef414c3d6e",
        "status" : "passed",
        "time" : {
          "start" : 1728092649804,
          "stop" : 1728092650450,
          "duration" : 646
        }
      }, {
        "uid" : "73a1bb5f825bf31c",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/73a1bb5f825bf31c",
        "status" : "passed",
        "time" : {
          "start" : 1728006353689,
          "stop" : 1728006354341,
          "duration" : 652
        }
      }, {
        "uid" : "1e48b31aec7da21a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/1e48b31aec7da21a",
        "status" : "passed",
        "time" : {
          "start" : 1727919945072,
          "stop" : 1727919945767,
          "duration" : 695
        }
      }, {
        "uid" : "cc76c0d71c4febe2",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/cc76c0d71c4febe2",
        "status" : "passed",
        "time" : {
          "start" : 1727833469526,
          "stop" : 1727833470176,
          "duration" : 650
        }
      }, {
        "uid" : "cc80d5c5aa12efc3",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/cc80d5c5aa12efc3",
        "status" : "passed",
        "time" : {
          "start" : 1727747606198,
          "stop" : 1727747606849,
          "duration" : 651
        }
      }, {
        "uid" : "28f3cda59b2de359",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/28f3cda59b2de359",
        "status" : "passed",
        "time" : {
          "start" : 1727660887439,
          "stop" : 1727660888091,
          "duration" : 652
        }
      }, {
        "uid" : "18397dd35317dc6c",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/18397dd35317dc6c",
        "status" : "passed",
        "time" : {
          "start" : 1727574698012,
          "stop" : 1727574698706,
          "duration" : 694
        }
      }, {
        "uid" : "7044b4b18e4df05f",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/7044b4b18e4df05f",
        "status" : "passed",
        "time" : {
          "start" : 1727487940436,
          "stop" : 1727487941083,
          "duration" : 647
        }
      }, {
        "uid" : "b2bceb316fa5c03d",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/b2bceb316fa5c03d",
        "status" : "passed",
        "time" : {
          "start" : 1727401561291,
          "stop" : 1727401561965,
          "duration" : 674
        }
      }, {
        "uid" : "5651e6d373240100",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/5651e6d373240100",
        "status" : "passed",
        "time" : {
          "start" : 1727315083887,
          "stop" : 1727315084550,
          "duration" : 663
        }
      }, {
        "uid" : "e6fb5b678f008978",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/e6fb5b678f008978",
        "status" : "passed",
        "time" : {
          "start" : 1727228765292,
          "stop" : 1727228765946,
          "duration" : 654
        }
      }, {
        "uid" : "af74e713d5f348f9",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/af74e713d5f348f9",
        "status" : "passed",
        "time" : {
          "start" : 1727142318495,
          "stop" : 1727142319143,
          "duration" : 648
        }
      }, {
        "uid" : "7aa1c27110c0cf9d",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/7aa1c27110c0cf9d",
        "status" : "passed",
        "time" : {
          "start" : 1727055865841,
          "stop" : 1727055866485,
          "duration" : 644
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "678bbd11279fa1ca.json",
  "parameterValues" : [ ]
}