{
  "uid" : "6fc8d6b9fb55cc16",
  "name" : "Checking the possibility of authorization with incorrect data",
  "fullName" : "tests.authorisation_page_test.TestAuthorizedUserPage#test_auth_user_with_wrong_password",
  "historyId" : "4b03ea5faa5e83a4d2234cc1422bdcfd",
  "time" : {
    "start" : 1728784098545,
    "stop" : 1728784098545,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5557acebc02a <unknown>\n#1 0x5557acba25e0 <unknown>\n#2 0x5557acb9a7eb <unknown>\n#3 0x5557acb8aa09 <unknown>\n#4 0x5557acb8c744 <unknown>\n#5 0x5557acb8acbd <unknown>\n#6 0x5557acb8a52f <unknown>\n#7 0x5557acb8a422 <unknown>\n#8 0x5557acb88493 <unknown>\n#9 0x5557acb88ada <unknown>\n#10 0x5557acba4f41 <unknown>\n#11 0x5557acc368c5 <unknown>\n#12 0x5557acc16b22 <unknown>\n#13 0x5557acc35d7d <unknown>\n#14 0x5557acc168c3 <unknown>\n#15 0x5557acbe46b3 <unknown>\n#16 0x5557acbe568e <unknown>\n#17 0x5557ace86a2b <unknown>\n#18 0x5557ace8a9b1 <unknown>\n#19 0x5557ace73225 <unknown>\n#20 0x5557ace8b532 <unknown>\n#21 0x5557ace5838f <unknown>\n#22 0x5557aceaaf28 <unknown>\n#23 0x5557aceab0f3 <unknown>\n#24 0x5557acebae7c <unknown>\n#25 0x7f7122e94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8218c2ce2701827a29a2b59dacbaa1a4\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7faf1f906240>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x5557aceab0f3 \\\\u003Cunknown>\\\\n#24 0x5557acebae7c \\\\u003Cunknown>\\\\n#25 0x7f7122e94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x5557acebc02a <unknown>\nE       #1 0x5557acba25e0 <unknown>\nE       #2 0x5557acb9a7eb <unknown>\nE       #3 0x5557acb8aa09 <unknown>\nE       #4 0x5557acb8c744 <unknown>\nE       #5 0x5557acb8acbd <unknown>\nE       #6 0x5557acb8a52f <unknown>\nE       #7 0x5557acb8a422 <unknown>\nE       #8 0x5557acb88493 <unknown>\nE       #9 0x5557acb88ada <unknown>\nE       #10 0x5557acba4f41 <unknown>\nE       #11 0x5557acc368c5 <unknown>\nE       #12 0x5557acc16b22 <unknown>\nE       #13 0x5557acc35d7d <unknown>\nE       #14 0x5557acc168c3 <unknown>\nE       #15 0x5557acbe46b3 <unknown>\nE       #16 0x5557acbe568e <unknown>\nE       #17 0x5557ace86a2b <unknown>\nE       #18 0x5557ace8a9b1 <unknown>\nE       #19 0x5557ace73225 <unknown>\nE       #20 0x5557ace8b532 <unknown>\nE       #21 0x5557ace5838f <unknown>\nE       #22 0x5557aceaaf28 <unknown>\nE       #23 0x5557aceab0f3 <unknown>\nE       #24 0x5557acebae7c <unknown>\nE       #25 0x7f7122e94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728784074935,
      "stop" : 1728784074936,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728784098546,
      "stop" : 1728784099318,
      "duration" : 772
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728784099319,
      "stop" : 1728784099747,
      "duration" : 428
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5557acebc02a <unknown>\n#1 0x5557acba25e0 <unknown>\n#2 0x5557acb9a7eb <unknown>\n#3 0x5557acb8aa09 <unknown>\n#4 0x5557acb8c744 <unknown>\n#5 0x5557acb8acbd <unknown>\n#6 0x5557acb8a52f <unknown>\n#7 0x5557acb8a422 <unknown>\n#8 0x5557acb88493 <unknown>\n#9 0x5557acb88ada <unknown>\n#10 0x5557acba4f41 <unknown>\n#11 0x5557acc368c5 <unknown>\n#12 0x5557acc16b22 <unknown>\n#13 0x5557acc35d7d <unknown>\n#14 0x5557acc168c3 <unknown>\n#15 0x5557acbe46b3 <unknown>\n#16 0x5557acbe568e <unknown>\n#17 0x5557ace86a2b <unknown>\n#18 0x5557ace8a9b1 <unknown>\n#19 0x5557ace73225 <unknown>\n#20 0x5557ace8b532 <unknown>\n#21 0x5557ace5838f <unknown>\n#22 0x5557aceaaf28 <unknown>\n#23 0x5557aceab0f3 <unknown>\n#24 0x5557acebae7c <unknown>\n#25 0x7f7122e94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728784099319,
        "stop" : 1728784099746,
        "duration" : 427
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x5557acebc02a <unknown>\n#1 0x5557acba25e0 <unknown>\n#2 0x5557acb9a7eb <unknown>\n#3 0x5557acb8aa09 <unknown>\n#4 0x5557acb8c744 <unknown>\n#5 0x5557acb8acbd <unknown>\n#6 0x5557acb8a52f <unknown>\n#7 0x5557acb8a422 <unknown>\n#8 0x5557acb88493 <unknown>\n#9 0x5557acb88ada <unknown>\n#10 0x5557acba4f41 <unknown>\n#11 0x5557acc368c5 <unknown>\n#12 0x5557acc16b22 <unknown>\n#13 0x5557acc35d7d <unknown>\n#14 0x5557acc168c3 <unknown>\n#15 0x5557acbe46b3 <unknown>\n#16 0x5557acbe568e <unknown>\n#17 0x5557ace86a2b <unknown>\n#18 0x5557ace8a9b1 <unknown>\n#19 0x5557ace73225 <unknown>\n#20 0x5557ace8b532 <unknown>\n#21 0x5557ace5838f <unknown>\n#22 0x5557aceaaf28 <unknown>\n#23 0x5557aceab0f3 <unknown>\n#24 0x5557acebae7c <unknown>\n#25 0x7f7122e94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"8218c2ce2701827a29a2b59dacbaa1a4\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728784099777,
      "stop" : 1728784099841,
      "duration" : 64
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Authorized User Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "authorisation_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestAuthorizedUserPage"
  }, {
    "name" : "host",
    "value" : "fv-az891-551"
  }, {
    "name" : "thread",
    "value" : "2367-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.authorisation_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 3,
        "skipped" : 0,
        "passed" : 58,
        "unknown" : 0,
        "total" : 61
      },
      "items" : [ {
        "uid" : "5866140c8dd8b5f5",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/60//#testresult/5866140c8dd8b5f5",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x56550b45902a <unknown>\n#1 0x56550b13f5e0 <unknown>\n#2 0x56550b1377eb <unknown>\n#3 0x56550b127a09 <unknown>\n#4 0x56550b129744 <unknown>\n#5 0x56550b127cbd <unknown>\n#6 0x56550b12752f <unknown>\n#7 0x56550b127422 <unknown>\n#8 0x56550b125493 <unknown>\n#9 0x56550b125ada <unknown>\n#10 0x56550b141f41 <unknown>\n#11 0x56550b1d38c5 <unknown>\n#12 0x56550b1b3b22 <unknown>\n#13 0x56550b1d2d7d <unknown>\n#14 0x56550b1b38c3 <unknown>\n#15 0x56550b1816b3 <unknown>\n#16 0x56550b18268e <unknown>\n#17 0x56550b423a2b <unknown>\n#18 0x56550b4279b1 <unknown>\n#19 0x56550b410225 <unknown>\n#20 0x56550b428532 <unknown>\n#21 0x56550b3f538f <unknown>\n#22 0x56550b447f28 <unknown>\n#23 0x56550b4480f3 <unknown>\n#24 0x56550b457e7c <unknown>\n#25 0x7f7988694ac3 <unknown>",
        "time" : {
          "start" : 1728697212551,
          "stop" : 1728697212551,
          "duration" : 0
        }
      }, {
        "uid" : "d7d96c043b897747",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/d7d96c043b897747",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55fd272aa02a <unknown>\n#1 0x55fd26f905e0 <unknown>\n#2 0x55fd26f887eb <unknown>\n#3 0x55fd26f78a09 <unknown>\n#4 0x55fd26f7a744 <unknown>\n#5 0x55fd26f78cbd <unknown>\n#6 0x55fd26f7852f <unknown>\n#7 0x55fd26f78422 <unknown>\n#8 0x55fd26f76493 <unknown>\n#9 0x55fd26f76ada <unknown>\n#10 0x55fd26f92f41 <unknown>\n#11 0x55fd270248c5 <unknown>\n#12 0x55fd27004b22 <unknown>\n#13 0x55fd27023d7d <unknown>\n#14 0x55fd270048c3 <unknown>\n#15 0x55fd26fd26b3 <unknown>\n#16 0x55fd26fd368e <unknown>\n#17 0x55fd27274a2b <unknown>\n#18 0x55fd272789b1 <unknown>\n#19 0x55fd27261225 <unknown>\n#20 0x55fd27279532 <unknown>\n#21 0x55fd2724638f <unknown>\n#22 0x55fd27298f28 <unknown>\n#23 0x55fd272990f3 <unknown>\n#24 0x55fd272a8e7c <unknown>\n#25 0x7f1e3c094ac3 <unknown>",
        "time" : {
          "start" : 1728610903897,
          "stop" : 1728610903897,
          "duration" : 0
        }
      }, {
        "uid" : "aee7dd986bd7977e",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/aee7dd986bd7977e",
        "status" : "passed",
        "time" : {
          "start" : 1728524534962,
          "stop" : 1728524535876,
          "duration" : 914
        }
      }, {
        "uid" : "4b476e9941d15762",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/4b476e9941d15762",
        "status" : "passed",
        "time" : {
          "start" : 1728438107374,
          "stop" : 1728438108285,
          "duration" : 911
        }
      }, {
        "uid" : "7ab3daf8c671cd7a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/7ab3daf8c671cd7a",
        "status" : "passed",
        "time" : {
          "start" : 1728351762126,
          "stop" : 1728351763055,
          "duration" : 929
        }
      }, {
        "uid" : "19983987c90a92aa",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/19983987c90a92aa",
        "status" : "passed",
        "time" : {
          "start" : 1728265539691,
          "stop" : 1728265540634,
          "duration" : 943
        }
      }, {
        "uid" : "a0544e41488fb6b7",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/a0544e41488fb6b7",
        "status" : "passed",
        "time" : {
          "start" : 1728179320985,
          "stop" : 1728179321892,
          "duration" : 907
        }
      }, {
        "uid" : "44fa56130ed1e2b5",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/44fa56130ed1e2b5",
        "status" : "passed",
        "time" : {
          "start" : 1728092474186,
          "stop" : 1728092475100,
          "duration" : 914
        }
      }, {
        "uid" : "d12fcdec2ab8a325",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/d12fcdec2ab8a325",
        "status" : "passed",
        "time" : {
          "start" : 1728006179999,
          "stop" : 1728006180920,
          "duration" : 921
        }
      }, {
        "uid" : "d022834f5a087186",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/d022834f5a087186",
        "status" : "passed",
        "time" : {
          "start" : 1727919766722,
          "stop" : 1727919767653,
          "duration" : 931
        }
      }, {
        "uid" : "81c1621470538c3d",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/81c1621470538c3d",
        "status" : "passed",
        "time" : {
          "start" : 1727833331182,
          "stop" : 1727833332119,
          "duration" : 937
        }
      }, {
        "uid" : "6db560a7248669d6",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/6db560a7248669d6",
        "status" : "passed",
        "time" : {
          "start" : 1727747466971,
          "stop" : 1727747467885,
          "duration" : 914
        }
      }, {
        "uid" : "bd839ff61cd0cd52",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/bd839ff61cd0cd52",
        "status" : "passed",
        "time" : {
          "start" : 1727660749124,
          "stop" : 1727660750062,
          "duration" : 938
        }
      }, {
        "uid" : "4aedf09e4235a930",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/4aedf09e4235a930",
        "status" : "passed",
        "time" : {
          "start" : 1727574548674,
          "stop" : 1727574549601,
          "duration" : 927
        }
      }, {
        "uid" : "ed83a3ac3e30583e",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/ed83a3ac3e30583e",
        "status" : "passed",
        "time" : {
          "start" : 1727487803138,
          "stop" : 1727487804094,
          "duration" : 956
        }
      }, {
        "uid" : "1fb3f89ac401b918",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/1fb3f89ac401b918",
        "status" : "passed",
        "time" : {
          "start" : 1727401360614,
          "stop" : 1727401361497,
          "duration" : 883
        }
      }, {
        "uid" : "8416becfaa13ba24",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/8416becfaa13ba24",
        "status" : "passed",
        "time" : {
          "start" : 1727314907727,
          "stop" : 1727314908600,
          "duration" : 873
        }
      }, {
        "uid" : "41ee876d256e00e8",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/41ee876d256e00e8",
        "status" : "passed",
        "time" : {
          "start" : 1727228609760,
          "stop" : 1727228610675,
          "duration" : 915
        }
      }, {
        "uid" : "fb6f486ccd35d6cd",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/fb6f486ccd35d6cd",
        "status" : "passed",
        "time" : {
          "start" : 1727142172216,
          "stop" : 1727142173194,
          "duration" : 978
        }
      }, {
        "uid" : "c078cef78589730f",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/c078cef78589730f",
        "status" : "passed",
        "time" : {
          "start" : 1727055730155,
          "stop" : 1727055731046,
          "duration" : 891
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "6fc8d6b9fb55cc16.json",
  "parameterValues" : [ ]
}