{
  "uid" : "3cf9d0088840e866",
  "name" : "Verify that the 'All Specialists' link leads an authorized user \n                         to the correct page after clicking",
  "fullName" : "tests.specialists_page_test.TestSpecialistPageLinks#test_sp_03_03_verify_all_specialists_link_leads_authorized_user_to_the_correct_page",
  "historyId" : "a700a0fce4c3e2666e471508243072ed",
  "time" : {
    "start" : 1728697327720,
    "stop" : 1728697327720,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55fb2c83a02a <unknown>\n#1 0x55fb2c5205e0 <unknown>\n#2 0x55fb2c5187eb <unknown>\n#3 0x55fb2c508a09 <unknown>\n#4 0x55fb2c50a744 <unknown>\n#5 0x55fb2c508cbd <unknown>\n#6 0x55fb2c50852f <unknown>\n#7 0x55fb2c508422 <unknown>\n#8 0x55fb2c506493 <unknown>\n#9 0x55fb2c506ada <unknown>\n#10 0x55fb2c522f41 <unknown>\n#11 0x55fb2c5b48c5 <unknown>\n#12 0x55fb2c594b22 <unknown>\n#13 0x55fb2c5b3d7d <unknown>\n#14 0x55fb2c5948c3 <unknown>\n#15 0x55fb2c5626b3 <unknown>\n#16 0x55fb2c56368e <unknown>\n#17 0x55fb2c804a2b <unknown>\n#18 0x55fb2c8089b1 <unknown>\n#19 0x55fb2c7f1225 <unknown>\n#20 0x55fb2c809532 <unknown>\n#21 0x55fb2c7d638f <unknown>\n#22 0x55fb2c828f28 <unknown>\n#23 0x55fb2c8290f3 <unknown>\n#24 0x55fb2c838e7c <unknown>\n#25 0x7f88c6c94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"db8a5bf936da7f48db70fff7b219970b\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f4df4e63170>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55fb2c8290f3 \\\\u003Cunknown>\\\\n#24 0x55fb2c838e7c \\\\u003Cunknown>\\\\n#25 0x7f88c6c94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55fb2c83a02a <unknown>\nE       #1 0x55fb2c5205e0 <unknown>\nE       #2 0x55fb2c5187eb <unknown>\nE       #3 0x55fb2c508a09 <unknown>\nE       #4 0x55fb2c50a744 <unknown>\nE       #5 0x55fb2c508cbd <unknown>\nE       #6 0x55fb2c50852f <unknown>\nE       #7 0x55fb2c508422 <unknown>\nE       #8 0x55fb2c506493 <unknown>\nE       #9 0x55fb2c506ada <unknown>\nE       #10 0x55fb2c522f41 <unknown>\nE       #11 0x55fb2c5b48c5 <unknown>\nE       #12 0x55fb2c594b22 <unknown>\nE       #13 0x55fb2c5b3d7d <unknown>\nE       #14 0x55fb2c5948c3 <unknown>\nE       #15 0x55fb2c5626b3 <unknown>\nE       #16 0x55fb2c56368e <unknown>\nE       #17 0x55fb2c804a2b <unknown>\nE       #18 0x55fb2c8089b1 <unknown>\nE       #19 0x55fb2c7f1225 <unknown>\nE       #20 0x55fb2c809532 <unknown>\nE       #21 0x55fb2c7d638f <unknown>\nE       #22 0x55fb2c828f28 <unknown>\nE       #23 0x55fb2c8290f3 <unknown>\nE       #24 0x55fb2c838e7c <unknown>\nE       #25 0x7f88c6c94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728697328493,
      "stop" : 1728697328916,
      "duration" : 423
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55fb2c83a02a <unknown>\n#1 0x55fb2c5205e0 <unknown>\n#2 0x55fb2c5187eb <unknown>\n#3 0x55fb2c508a09 <unknown>\n#4 0x55fb2c50a744 <unknown>\n#5 0x55fb2c508cbd <unknown>\n#6 0x55fb2c50852f <unknown>\n#7 0x55fb2c508422 <unknown>\n#8 0x55fb2c506493 <unknown>\n#9 0x55fb2c506ada <unknown>\n#10 0x55fb2c522f41 <unknown>\n#11 0x55fb2c5b48c5 <unknown>\n#12 0x55fb2c594b22 <unknown>\n#13 0x55fb2c5b3d7d <unknown>\n#14 0x55fb2c5948c3 <unknown>\n#15 0x55fb2c5626b3 <unknown>\n#16 0x55fb2c56368e <unknown>\n#17 0x55fb2c804a2b <unknown>\n#18 0x55fb2c8089b1 <unknown>\n#19 0x55fb2c7f1225 <unknown>\n#20 0x55fb2c809532 <unknown>\n#21 0x55fb2c7d638f <unknown>\n#22 0x55fb2c828f28 <unknown>\n#23 0x55fb2c8290f3 <unknown>\n#24 0x55fb2c838e7c <unknown>\n#25 0x7f88c6c94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728697328493,
        "stop" : 1728697328916,
        "duration" : 423
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55fb2c83a02a <unknown>\n#1 0x55fb2c5205e0 <unknown>\n#2 0x55fb2c5187eb <unknown>\n#3 0x55fb2c508a09 <unknown>\n#4 0x55fb2c50a744 <unknown>\n#5 0x55fb2c508cbd <unknown>\n#6 0x55fb2c50852f <unknown>\n#7 0x55fb2c508422 <unknown>\n#8 0x55fb2c506493 <unknown>\n#9 0x55fb2c506ada <unknown>\n#10 0x55fb2c522f41 <unknown>\n#11 0x55fb2c5b48c5 <unknown>\n#12 0x55fb2c594b22 <unknown>\n#13 0x55fb2c5b3d7d <unknown>\n#14 0x55fb2c5948c3 <unknown>\n#15 0x55fb2c5626b3 <unknown>\n#16 0x55fb2c56368e <unknown>\n#17 0x55fb2c804a2b <unknown>\n#18 0x55fb2c8089b1 <unknown>\n#19 0x55fb2c7f1225 <unknown>\n#20 0x55fb2c809532 <unknown>\n#21 0x55fb2c7d638f <unknown>\n#22 0x55fb2c828f28 <unknown>\n#23 0x55fb2c8290f3 <unknown>\n#24 0x55fb2c838e7c <unknown>\n#25 0x7f88c6c94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"db8a5bf936da7f48db70fff7b219970b\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728697327720,
      "stop" : 1728697328493,
      "duration" : 773
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728697167335,
      "stop" : 1728697167335,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728697328949,
      "stop" : 1728697329011,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Specialists Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "specialists_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestSpecialistsPage"
  }, {
    "name" : "host",
    "value" : "fv-az570-490"
  }, {
    "name" : "thread",
    "value" : "2304-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.specialists_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 7,
        "skipped" : 0,
        "passed" : 23,
        "unknown" : 0,
        "total" : 30
      },
      "items" : [ {
        "uid" : "48bd05a4a064a6",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/48bd05a4a064a6",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55744328c02a <unknown>\n#1 0x557442f725e0 <unknown>\n#2 0x557442f6a7eb <unknown>\n#3 0x557442f5aa09 <unknown>\n#4 0x557442f5c744 <unknown>\n#5 0x557442f5acbd <unknown>\n#6 0x557442f5a52f <unknown>\n#7 0x557442f5a422 <unknown>\n#8 0x557442f58493 <unknown>\n#9 0x557442f58ada <unknown>\n#10 0x557442f74f41 <unknown>\n#11 0x5574430068c5 <unknown>\n#12 0x557442fe6b22 <unknown>\n#13 0x557443005d7d <unknown>\n#14 0x557442fe68c3 <unknown>\n#15 0x557442fb46b3 <unknown>\n#16 0x557442fb568e <unknown>\n#17 0x557443256a2b <unknown>\n#18 0x55744325a9b1 <unknown>\n#19 0x557443243225 <unknown>\n#20 0x55744325b532 <unknown>\n#21 0x55744322838f <unknown>\n#22 0x55744327af28 <unknown>\n#23 0x55744327b0f3 <unknown>\n#24 0x55744328ae7c <unknown>\n#25 0x7fd1ac894ac3 <unknown>",
        "time" : {
          "start" : 1728611018959,
          "stop" : 1728611018959,
          "duration" : 0
        }
      }, {
        "uid" : "bebb350b22b54875",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/bebb350b22b54875",
        "status" : "passed",
        "time" : {
          "start" : 1728525024077,
          "stop" : 1728525025776,
          "duration" : 1699
        }
      }, {
        "uid" : "5e5368802e6800d0",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/5e5368802e6800d0",
        "status" : "passed",
        "time" : {
          "start" : 1728438695556,
          "stop" : 1728438697223,
          "duration" : 1667
        }
      }, {
        "uid" : "c0aa635c6b7ef323",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/c0aa635c6b7ef323",
        "status" : "passed",
        "time" : {
          "start" : 1728352283230,
          "stop" : 1728352285477,
          "duration" : 2247
        }
      }, {
        "uid" : "db6157cf56eceb13",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/db6157cf56eceb13",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728266791296,
          "stop" : 1728266791296,
          "duration" : 0
        }
      }, {
        "uid" : "f9773850f44ab0f7",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/f9773850f44ab0f7",
        "status" : "passed",
        "time" : {
          "start" : 1728179826004,
          "stop" : 1728179828135,
          "duration" : 2131
        }
      }, {
        "uid" : "776c4d46c5d92ea6",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/776c4d46c5d92ea6",
        "status" : "passed",
        "time" : {
          "start" : 1728093070767,
          "stop" : 1728093073371,
          "duration" : 2604
        }
      }, {
        "uid" : "b94c26c5bf61d6c4",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/b94c26c5bf61d6c4",
        "status" : "passed",
        "time" : {
          "start" : 1728006774049,
          "stop" : 1728006776643,
          "duration" : 2594
        }
      }, {
        "uid" : "1268d719909834af",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/1268d719909834af",
        "status" : "passed",
        "time" : {
          "start" : 1727920421922,
          "stop" : 1727920424610,
          "duration" : 2688
        }
      }, {
        "uid" : "540947391858cdd8",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/540947391858cdd8",
        "status" : "passed",
        "time" : {
          "start" : 1727833857389,
          "stop" : 1727833859969,
          "duration" : 2580
        }
      }, {
        "uid" : "4bb95a61f1a986ab",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/4bb95a61f1a986ab",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('tag name', 'h2')\nStacktrace:\n#0 0x55816d4a113a <unknown>\n#1 0x55816d1875e0 <unknown>\n#2 0x55816d1d6be8 <unknown>\n#3 0x55816d1d6e81 <unknown>\n#4 0x55816d21d8c4 <unknown>\n#5 0x55816d1fbb4d <unknown>\n#6 0x55816d21ad7d <unknown>\n#7 0x55816d1fb8c3 <unknown>\n#8 0x55816d1c96b3 <unknown>\n#9 0x55816d1ca68e <unknown>\n#10 0x55816d46bb3b <unknown>\n#11 0x55816d46fac1 <unknown>\n#12 0x55816d458335 <unknown>\n#13 0x55816d470642 <unknown>\n#14 0x55816d43d49f <unknown>\n#15 0x55816d490038 <unknown>\n#16 0x55816d490203 <unknown>\n#17 0x55816d49ff8c <unknown>\n#18 0x7f58bd694ac3 <unknown>",
        "time" : {
          "start" : 1727747959526,
          "stop" : 1727747981109,
          "duration" : 21583
        }
      }, {
        "uid" : "cb0011b694a50499",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/cb0011b694a50499",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('tag name', 'h2')\nStacktrace:\n#0 0x5567d721813a <unknown>\n#1 0x5567d6efe5e0 <unknown>\n#2 0x5567d6f4dbe8 <unknown>\n#3 0x5567d6f4de81 <unknown>\n#4 0x5567d6f948c4 <unknown>\n#5 0x5567d6f72b4d <unknown>\n#6 0x5567d6f91d7d <unknown>\n#7 0x5567d6f728c3 <unknown>\n#8 0x5567d6f406b3 <unknown>\n#9 0x5567d6f4168e <unknown>\n#10 0x5567d71e2b3b <unknown>\n#11 0x5567d71e6ac1 <unknown>\n#12 0x5567d71cf335 <unknown>\n#13 0x5567d71e7642 <unknown>\n#14 0x5567d71b449f <unknown>\n#15 0x5567d7207038 <unknown>\n#16 0x5567d7207203 <unknown>\n#17 0x5567d7216f8c <unknown>\n#18 0x7f25e7894ac3 <unknown>",
        "time" : {
          "start" : 1727661241075,
          "stop" : 1727661262551,
          "duration" : 21476
        }
      }, {
        "uid" : "e1e0157f9898afa1",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/e1e0157f9898afa1",
        "status" : "passed",
        "time" : {
          "start" : 1727575062280,
          "stop" : 1727575064441,
          "duration" : 2161
        }
      }, {
        "uid" : "d907fff32c575c83",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/d907fff32c575c83",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1727488282335,
          "stop" : 1727488282335,
          "duration" : 0
        }
      }, {
        "uid" : "9b720110cadcbae0",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/9b720110cadcbae0",
        "status" : "passed",
        "time" : {
          "start" : 1727402042087,
          "stop" : 1727402044720,
          "duration" : 2633
        }
      }, {
        "uid" : "27114b586139bb12",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/27114b586139bb12",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('tag name', 'h2')\nStacktrace:\n#0 0x555b5a52113a <unknown>\n#1 0x555b5a2075e0 <unknown>\n#2 0x555b5a256be8 <unknown>\n#3 0x555b5a256e81 <unknown>\n#4 0x555b5a29d8c4 <unknown>\n#5 0x555b5a27bb4d <unknown>\n#6 0x555b5a29ad7d <unknown>\n#7 0x555b5a27b8c3 <unknown>\n#8 0x555b5a2496b3 <unknown>\n#9 0x555b5a24a68e <unknown>\n#10 0x555b5a4ebb3b <unknown>\n#11 0x555b5a4efac1 <unknown>\n#12 0x555b5a4d8335 <unknown>\n#13 0x555b5a4f0642 <unknown>\n#14 0x555b5a4bd49f <unknown>\n#15 0x555b5a510038 <unknown>\n#16 0x555b5a510203 <unknown>\n#17 0x555b5a51ff8c <unknown>\n#18 0x7f2d68894ac3 <unknown>",
        "time" : {
          "start" : 1727315515509,
          "stop" : 1727315537048,
          "duration" : 21539
        }
      }, {
        "uid" : "fb56260081ecbb8a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/fb56260081ecbb8a",
        "status" : "passed",
        "time" : {
          "start" : 1727229160790,
          "stop" : 1727229163431,
          "duration" : 2641
        }
      }, {
        "uid" : "97276e174e8a5d0a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/97276e174e8a5d0a",
        "status" : "passed",
        "time" : {
          "start" : 1727142689372,
          "stop" : 1727142690990,
          "duration" : 1618
        }
      }, {
        "uid" : "33bef28e6742fa0",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/33bef28e6742fa0",
        "status" : "passed",
        "time" : {
          "start" : 1727056208119,
          "stop" : 1727056209674,
          "duration" : 1555
        }
      }, {
        "uid" : "f80fb27529f61636",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/40//#testresult/f80fb27529f61636",
        "status" : "passed",
        "time" : {
          "start" : 1726970137668,
          "stop" : 1726970139223,
          "duration" : 1555
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "3cf9d0088840e866.json",
  "parameterValues" : [ ]
}