{
  "uid" : "5919a8a3b8f77819",
  "name" : "Check statistic table.",
  "fullName" : "tests.test_speech_exercises_ru.TestCardsRU#test_get_statistic_data",
  "historyId" : "15df626f86a935fbcd917f7ea4002a26",
  "time" : {
    "start" : 1728697362640,
    "stop" : 1728697362640,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55afa953d02a <unknown>\n#1 0x55afa92235e0 <unknown>\n#2 0x55afa921b7eb <unknown>\n#3 0x55afa920ba09 <unknown>\n#4 0x55afa920d744 <unknown>\n#5 0x55afa920bcbd <unknown>\n#6 0x55afa920b52f <unknown>\n#7 0x55afa920b422 <unknown>\n#8 0x55afa9209493 <unknown>\n#9 0x55afa9209ada <unknown>\n#10 0x55afa9225f41 <unknown>\n#11 0x55afa92b78c5 <unknown>\n#12 0x55afa9297b22 <unknown>\n#13 0x55afa92b6d7d <unknown>\n#14 0x55afa92978c3 <unknown>\n#15 0x55afa92656b3 <unknown>\n#16 0x55afa926668e <unknown>\n#17 0x55afa9507a2b <unknown>\n#18 0x55afa950b9b1 <unknown>\n#19 0x55afa94f4225 <unknown>\n#20 0x55afa950c532 <unknown>\n#21 0x55afa94d938f <unknown>\n#22 0x55afa952bf28 <unknown>\n#23 0x55afa952c0f3 <unknown>\n#24 0x55afa953be7c <unknown>\n#25 0x7f3d2f694ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a7e49051548a3a8c88e183f6f03db0e0\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f4df4d87800>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55afa952c0f3 \\\\u003Cunknown>\\\\n#24 0x55afa953be7c \\\\u003Cunknown>\\\\n#25 0x7f3d2f694ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55afa953d02a <unknown>\nE       #1 0x55afa92235e0 <unknown>\nE       #2 0x55afa921b7eb <unknown>\nE       #3 0x55afa920ba09 <unknown>\nE       #4 0x55afa920d744 <unknown>\nE       #5 0x55afa920bcbd <unknown>\nE       #6 0x55afa920b52f <unknown>\nE       #7 0x55afa920b422 <unknown>\nE       #8 0x55afa9209493 <unknown>\nE       #9 0x55afa9209ada <unknown>\nE       #10 0x55afa9225f41 <unknown>\nE       #11 0x55afa92b78c5 <unknown>\nE       #12 0x55afa9297b22 <unknown>\nE       #13 0x55afa92b6d7d <unknown>\nE       #14 0x55afa92978c3 <unknown>\nE       #15 0x55afa92656b3 <unknown>\nE       #16 0x55afa926668e <unknown>\nE       #17 0x55afa9507a2b <unknown>\nE       #18 0x55afa950b9b1 <unknown>\nE       #19 0x55afa94f4225 <unknown>\nE       #20 0x55afa950c532 <unknown>\nE       #21 0x55afa94d938f <unknown>\nE       #22 0x55afa952bf28 <unknown>\nE       #23 0x55afa952c0f3 <unknown>\nE       #24 0x55afa953be7c <unknown>\nE       #25 0x7f3d2f694ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728697363412,
      "stop" : 1728697363837,
      "duration" : 425
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55afa953d02a <unknown>\n#1 0x55afa92235e0 <unknown>\n#2 0x55afa921b7eb <unknown>\n#3 0x55afa920ba09 <unknown>\n#4 0x55afa920d744 <unknown>\n#5 0x55afa920bcbd <unknown>\n#6 0x55afa920b52f <unknown>\n#7 0x55afa920b422 <unknown>\n#8 0x55afa9209493 <unknown>\n#9 0x55afa9209ada <unknown>\n#10 0x55afa9225f41 <unknown>\n#11 0x55afa92b78c5 <unknown>\n#12 0x55afa9297b22 <unknown>\n#13 0x55afa92b6d7d <unknown>\n#14 0x55afa92978c3 <unknown>\n#15 0x55afa92656b3 <unknown>\n#16 0x55afa926668e <unknown>\n#17 0x55afa9507a2b <unknown>\n#18 0x55afa950b9b1 <unknown>\n#19 0x55afa94f4225 <unknown>\n#20 0x55afa950c532 <unknown>\n#21 0x55afa94d938f <unknown>\n#22 0x55afa952bf28 <unknown>\n#23 0x55afa952c0f3 <unknown>\n#24 0x55afa953be7c <unknown>\n#25 0x7f3d2f694ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728697363413,
        "stop" : 1728697363836,
        "duration" : 423
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55afa953d02a <unknown>\n#1 0x55afa92235e0 <unknown>\n#2 0x55afa921b7eb <unknown>\n#3 0x55afa920ba09 <unknown>\n#4 0x55afa920d744 <unknown>\n#5 0x55afa920bcbd <unknown>\n#6 0x55afa920b52f <unknown>\n#7 0x55afa920b422 <unknown>\n#8 0x55afa9209493 <unknown>\n#9 0x55afa9209ada <unknown>\n#10 0x55afa9225f41 <unknown>\n#11 0x55afa92b78c5 <unknown>\n#12 0x55afa9297b22 <unknown>\n#13 0x55afa92b6d7d <unknown>\n#14 0x55afa92978c3 <unknown>\n#15 0x55afa92656b3 <unknown>\n#16 0x55afa926668e <unknown>\n#17 0x55afa9507a2b <unknown>\n#18 0x55afa950b9b1 <unknown>\n#19 0x55afa94f4225 <unknown>\n#20 0x55afa950c532 <unknown>\n#21 0x55afa94d938f <unknown>\n#22 0x55afa952bf28 <unknown>\n#23 0x55afa952c0f3 <unknown>\n#24 0x55afa953be7c <unknown>\n#25 0x7f3d2f694ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"a7e49051548a3a8c88e183f6f03db0e0\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728697362640,
      "stop" : 1728697363412,
      "duration" : 772
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728697167335,
      "stop" : 1728697167335,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728697363888,
      "stop" : 1728697363950,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Statistic."
  }, {
    "name" : "epic",
    "value" : "Speech exercises."
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "subSuite",
    "value" : "TestCardsRU"
  }, {
    "name" : "host",
    "value" : "fv-az570-490"
  }, {
    "name" : "thread",
    "value" : "2304-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_speech_exercises_ru"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 12,
        "passed" : 48,
        "unknown" : 0,
        "total" : 60
      },
      "items" : [ {
        "uid" : "1565010d90e798c9",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/1565010d90e798c9",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x558b1058e02a <unknown>\n#1 0x558b102745e0 <unknown>\n#2 0x558b1026c7eb <unknown>\n#3 0x558b1025ca09 <unknown>\n#4 0x558b1025e744 <unknown>\n#5 0x558b1025ccbd <unknown>\n#6 0x558b1025c52f <unknown>\n#7 0x558b1025c422 <unknown>\n#8 0x558b1025a493 <unknown>\n#9 0x558b1025aada <unknown>\n#10 0x558b10276f41 <unknown>\n#11 0x558b103088c5 <unknown>\n#12 0x558b102e8b22 <unknown>\n#13 0x558b10307d7d <unknown>\n#14 0x558b102e88c3 <unknown>\n#15 0x558b102b66b3 <unknown>\n#16 0x558b102b768e <unknown>\n#17 0x558b10558a2b <unknown>\n#18 0x558b1055c9b1 <unknown>\n#19 0x558b10545225 <unknown>\n#20 0x558b1055d532 <unknown>\n#21 0x558b1052a38f <unknown>\n#22 0x558b1057cf28 <unknown>\n#23 0x558b1057d0f3 <unknown>\n#24 0x558b1058ce7c <unknown>\n#25 0x7f1159a94ac3 <unknown>",
        "time" : {
          "start" : 1728611053891,
          "stop" : 1728611053891,
          "duration" : 0
        }
      }, {
        "uid" : "b31a12b9ee3dfbe3",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/b31a12b9ee3dfbe3",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728525329381,
          "stop" : 1728525330737,
          "duration" : 1356
        }
      }, {
        "uid" : "b2d6fc86b13e4b78",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/b2d6fc86b13e4b78",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728439159439,
          "stop" : 1728439160848,
          "duration" : 1409
        }
      }, {
        "uid" : "cf287ccc39118ac6",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/cf287ccc39118ac6",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728352601388,
          "stop" : 1728352602803,
          "duration" : 1415
        }
      }, {
        "uid" : "771e32a0e18b14c3",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/771e32a0e18b14c3",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728267492635,
          "stop" : 1728267492635,
          "duration" : 0
        }
      }, {
        "uid" : "be17ff60bcdd36d5",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/be17ff60bcdd36d5",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728180137979,
          "stop" : 1728180139380,
          "duration" : 1401
        }
      }, {
        "uid" : "8a11b13374e8d47f",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/8a11b13374e8d47f",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728093427365,
          "stop" : 1728093429223,
          "duration" : 1858
        }
      }, {
        "uid" : "97dfa2859f4b916a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/97dfa2859f4b916a",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728007133089,
          "stop" : 1728007134937,
          "duration" : 1848
        }
      }, {
        "uid" : "88b3bb6ab459d020",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/88b3bb6ab459d020",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1727920923901,
          "stop" : 1727920923901,
          "duration" : 0
        }
      }, {
        "uid" : "4cf38f3e35d39d71",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/4cf38f3e35d39d71",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find elements by locator ('xpath', '//tbody/tr')",
        "time" : {
          "start" : 1727834285844,
          "stop" : 1727834307272,
          "duration" : 21428
        }
      }, {
        "uid" : "80bf78909d41bd3a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/80bf78909d41bd3a",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1727748408627,
          "stop" : 1727748408627,
          "duration" : 0
        }
      }, {
        "uid" : "5b92cf3d1f544f30",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/5b92cf3d1f544f30",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727661717809,
          "stop" : 1727661720829,
          "duration" : 3020
        }
      }, {
        "uid" : "44c1ed19b9be2ab4",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/44c1ed19b9be2ab4",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1727575574398,
          "stop" : 1727575574398,
          "duration" : 0
        }
      }, {
        "uid" : "355e2ae2a3a64509",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/355e2ae2a3a64509",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727488972109,
          "stop" : 1727488975503,
          "duration" : 3394
        }
      }, {
        "uid" : "1acd1bad91e9e366",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/1acd1bad91e9e366",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1727402579944,
          "stop" : 1727402579944,
          "duration" : 0
        }
      }, {
        "uid" : "721f3933333f27a2",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/721f3933333f27a2",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727316216844,
          "stop" : 1727316219640,
          "duration" : 2796
        }
      }, {
        "uid" : "d2567de988bb4a37",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/d2567de988bb4a37",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1727229739889,
          "stop" : 1727229739889,
          "duration" : 0
        }
      }, {
        "uid" : "69235c84e7078ed0",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/69235c84e7078ed0",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727143162327,
          "stop" : 1727143165270,
          "duration" : 2943
        }
      }, {
        "uid" : "a32216635da57ded",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/a32216635da57ded",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727056597694,
          "stop" : 1727056599538,
          "duration" : 1844
        }
      }, {
        "uid" : "464f93ad5971359d",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/40//#testresult/464f93ad5971359d",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1726970420781,
          "stop" : 1726970422184,
          "duration" : 1403
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail" ]
  },
  "source" : "5919a8a3b8f77819.json",
  "parameterValues" : [ ]
}