{
  "uid" : "acf5be1c4b5a466e",
  "name" : "Select a random card from \"Similar phrases\" group and compare UI vs BACKEND data",
  "fullName" : "tests.test_speech_exercises_en.TestCardsEN#test_random_cards_in_similar_phrases_en",
  "historyId" : "106afe14e1824ad4b55b346a52794d4b",
  "time" : {
    "start" : 1728697349727,
    "stop" : 1728697349727,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55aeaa33502a <unknown>\n#1 0x55aeaa01b5e0 <unknown>\n#2 0x55aeaa0137eb <unknown>\n#3 0x55aeaa003a09 <unknown>\n#4 0x55aeaa005744 <unknown>\n#5 0x55aeaa003cbd <unknown>\n#6 0x55aeaa00352f <unknown>\n#7 0x55aeaa003422 <unknown>\n#8 0x55aeaa001493 <unknown>\n#9 0x55aeaa001ada <unknown>\n#10 0x55aeaa01df41 <unknown>\n#11 0x55aeaa0af8c5 <unknown>\n#12 0x55aeaa08fb22 <unknown>\n#13 0x55aeaa0aed7d <unknown>\n#14 0x55aeaa08f8c3 <unknown>\n#15 0x55aeaa05d6b3 <unknown>\n#16 0x55aeaa05e68e <unknown>\n#17 0x55aeaa2ffa2b <unknown>\n#18 0x55aeaa3039b1 <unknown>\n#19 0x55aeaa2ec225 <unknown>\n#20 0x55aeaa304532 <unknown>\n#21 0x55aeaa2d138f <unknown>\n#22 0x55aeaa323f28 <unknown>\n#23 0x55aeaa3240f3 <unknown>\n#24 0x55aeaa333e7c <unknown>\n#25 0x7f04aec94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"1680a5d32a12aa3d0eefd819e57eefec\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f4df4ecb200>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x55aeaa3240f3 \\\\u003Cunknown>\\\\n#24 0x55aeaa333e7c \\\\u003Cunknown>\\\\n#25 0x7f04aec94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55aeaa33502a <unknown>\nE       #1 0x55aeaa01b5e0 <unknown>\nE       #2 0x55aeaa0137eb <unknown>\nE       #3 0x55aeaa003a09 <unknown>\nE       #4 0x55aeaa005744 <unknown>\nE       #5 0x55aeaa003cbd <unknown>\nE       #6 0x55aeaa00352f <unknown>\nE       #7 0x55aeaa003422 <unknown>\nE       #8 0x55aeaa001493 <unknown>\nE       #9 0x55aeaa001ada <unknown>\nE       #10 0x55aeaa01df41 <unknown>\nE       #11 0x55aeaa0af8c5 <unknown>\nE       #12 0x55aeaa08fb22 <unknown>\nE       #13 0x55aeaa0aed7d <unknown>\nE       #14 0x55aeaa08f8c3 <unknown>\nE       #15 0x55aeaa05d6b3 <unknown>\nE       #16 0x55aeaa05e68e <unknown>\nE       #17 0x55aeaa2ffa2b <unknown>\nE       #18 0x55aeaa3039b1 <unknown>\nE       #19 0x55aeaa2ec225 <unknown>\nE       #20 0x55aeaa304532 <unknown>\nE       #21 0x55aeaa2d138f <unknown>\nE       #22 0x55aeaa323f28 <unknown>\nE       #23 0x55aeaa3240f3 <unknown>\nE       #24 0x55aeaa333e7c <unknown>\nE       #25 0x7f04aec94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728697350497,
      "stop" : 1728697350918,
      "duration" : 421
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55aeaa33502a <unknown>\n#1 0x55aeaa01b5e0 <unknown>\n#2 0x55aeaa0137eb <unknown>\n#3 0x55aeaa003a09 <unknown>\n#4 0x55aeaa005744 <unknown>\n#5 0x55aeaa003cbd <unknown>\n#6 0x55aeaa00352f <unknown>\n#7 0x55aeaa003422 <unknown>\n#8 0x55aeaa001493 <unknown>\n#9 0x55aeaa001ada <unknown>\n#10 0x55aeaa01df41 <unknown>\n#11 0x55aeaa0af8c5 <unknown>\n#12 0x55aeaa08fb22 <unknown>\n#13 0x55aeaa0aed7d <unknown>\n#14 0x55aeaa08f8c3 <unknown>\n#15 0x55aeaa05d6b3 <unknown>\n#16 0x55aeaa05e68e <unknown>\n#17 0x55aeaa2ffa2b <unknown>\n#18 0x55aeaa3039b1 <unknown>\n#19 0x55aeaa2ec225 <unknown>\n#20 0x55aeaa304532 <unknown>\n#21 0x55aeaa2d138f <unknown>\n#22 0x55aeaa323f28 <unknown>\n#23 0x55aeaa3240f3 <unknown>\n#24 0x55aeaa333e7c <unknown>\n#25 0x7f04aec94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728697350497,
        "stop" : 1728697350918,
        "duration" : 421
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55aeaa33502a <unknown>\n#1 0x55aeaa01b5e0 <unknown>\n#2 0x55aeaa0137eb <unknown>\n#3 0x55aeaa003a09 <unknown>\n#4 0x55aeaa005744 <unknown>\n#5 0x55aeaa003cbd <unknown>\n#6 0x55aeaa00352f <unknown>\n#7 0x55aeaa003422 <unknown>\n#8 0x55aeaa001493 <unknown>\n#9 0x55aeaa001ada <unknown>\n#10 0x55aeaa01df41 <unknown>\n#11 0x55aeaa0af8c5 <unknown>\n#12 0x55aeaa08fb22 <unknown>\n#13 0x55aeaa0aed7d <unknown>\n#14 0x55aeaa08f8c3 <unknown>\n#15 0x55aeaa05d6b3 <unknown>\n#16 0x55aeaa05e68e <unknown>\n#17 0x55aeaa2ffa2b <unknown>\n#18 0x55aeaa3039b1 <unknown>\n#19 0x55aeaa2ec225 <unknown>\n#20 0x55aeaa304532 <unknown>\n#21 0x55aeaa2d138f <unknown>\n#22 0x55aeaa323f28 <unknown>\n#23 0x55aeaa3240f3 <unknown>\n#24 0x55aeaa333e7c <unknown>\n#25 0x7f04aec94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"1680a5d32a12aa3d0eefd819e57eefec\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728697349728,
      "stop" : 1728697350497,
      "duration" : 769
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728697167335,
      "stop" : 1728697167335,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728697350951,
      "stop" : 1728697351012,
      "duration" : 61
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Speech exercises EN."
  }, {
    "name" : "epic",
    "value" : "Speech exercises."
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "subSuite",
    "value" : "TestCardsEN"
  }, {
    "name" : "host",
    "value" : "fv-az570-490"
  }, {
    "name" : "thread",
    "value" : "2304-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_speech_exercises_en"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 7,
        "passed" : 53,
        "unknown" : 0,
        "total" : 60
      },
      "items" : [ {
        "uid" : "902fcab83587fb0b",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/902fcab83587fb0b",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x557a2e6c802a <unknown>\n#1 0x557a2e3ae5e0 <unknown>\n#2 0x557a2e3a67eb <unknown>\n#3 0x557a2e396a09 <unknown>\n#4 0x557a2e398744 <unknown>\n#5 0x557a2e396cbd <unknown>\n#6 0x557a2e39652f <unknown>\n#7 0x557a2e396422 <unknown>\n#8 0x557a2e394493 <unknown>\n#9 0x557a2e394ada <unknown>\n#10 0x557a2e3b0f41 <unknown>\n#11 0x557a2e4428c5 <unknown>\n#12 0x557a2e422b22 <unknown>\n#13 0x557a2e441d7d <unknown>\n#14 0x557a2e4228c3 <unknown>\n#15 0x557a2e3f06b3 <unknown>\n#16 0x557a2e3f168e <unknown>\n#17 0x557a2e692a2b <unknown>\n#18 0x557a2e6969b1 <unknown>\n#19 0x557a2e67f225 <unknown>\n#20 0x557a2e697532 <unknown>\n#21 0x557a2e66438f <unknown>\n#22 0x557a2e6b6f28 <unknown>\n#23 0x557a2e6b70f3 <unknown>\n#24 0x557a2e6c6e7c <unknown>\n#25 0x7fe2cf694ac3 <unknown>",
        "time" : {
          "start" : 1728611040897,
          "stop" : 1728611040897,
          "duration" : 0
        }
      }, {
        "uid" : "c029b846ef4113d2",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/c029b846ef4113d2",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728525115936,
          "stop" : 1728525124482,
          "duration" : 8546
        }
      }, {
        "uid" : "12691c1aee705f74",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/12691c1aee705f74",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728438787107,
          "stop" : 1728438795842,
          "duration" : 8735
        }
      }, {
        "uid" : "2aeb53605303ff5e",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/2aeb53605303ff5e",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728352382927,
          "stop" : 1728352391920,
          "duration" : 8993
        }
      }, {
        "uid" : "e46164931335caa",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/e46164931335caa",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728267038152,
          "stop" : 1728267038152,
          "duration" : 0
        }
      }, {
        "uid" : "63a7da5f84229183",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/63a7da5f84229183",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728179924342,
          "stop" : 1728179933180,
          "duration" : 8838
        }
      }, {
        "uid" : "e687aeda0f37a2cc",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/e687aeda0f37a2cc",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728093186012,
          "stop" : 1728093195620,
          "duration" : 9608
        }
      }, {
        "uid" : "441d3bd35d3fda4f",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/441d3bd35d3fda4f",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728006890554,
          "stop" : 1728006900208,
          "duration" : 9654
        }
      }, {
        "uid" : "d632634d8dc4e22c",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/d632634d8dc4e22c",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//button[@data-test-active-link=\"Similar phrases\"]')\nStacktrace:\n#0 0x5559a4d0b13a <unknown>\n#1 0x5559a49f15e0 <unknown>\n#2 0x5559a4a40be8 <unknown>\n#3 0x5559a4a40e81 <unknown>\n#4 0x5559a4a878c4 <unknown>\n#5 0x5559a4a65b4d <unknown>\n#6 0x5559a4a84d7d <unknown>\n#7 0x5559a4a658c3 <unknown>\n#8 0x5559a4a336b3 <unknown>\n#9 0x5559a4a3468e <unknown>\n#10 0x5559a4cd5b3b <unknown>\n#11 0x5559a4cd9ac1 <unknown>\n#12 0x5559a4cc2335 <unknown>\n#13 0x5559a4cda642 <unknown>\n#14 0x5559a4ca749f <unknown>\n#15 0x5559a4cfa038 <unknown>\n#16 0x5559a4cfa203 <unknown>\n#17 0x5559a4d09f8c <unknown>\n#18 0x7f27fec94ac3 <unknown>",
        "time" : {
          "start" : 1727920601136,
          "stop" : 1727920621288,
          "duration" : 20152
        }
      }, {
        "uid" : "114317ebda9d4909",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/114317ebda9d4909",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727833989928,
          "stop" : 1727834002567,
          "duration" : 12639
        }
      }, {
        "uid" : "743cbe00786ea0fd",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/743cbe00786ea0fd",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727748125620,
          "stop" : 1727748151920,
          "duration" : 26300
        }
      }, {
        "uid" : "e00bc15cd549b17a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/e00bc15cd549b17a",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727661403963,
          "stop" : 1727661415704,
          "duration" : 11741
        }
      }, {
        "uid" : "f13fc57de5f4455b",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/f13fc57de5f4455b",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727575254323,
          "stop" : 1727575265394,
          "duration" : 11071
        }
      }, {
        "uid" : "df88f0e0ee91078d",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/df88f0e0ee91078d",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727488488380,
          "stop" : 1727488536313,
          "duration" : 47933
        }
      }, {
        "uid" : "4948a538c5ae6cf8",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/4948a538c5ae6cf8",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727402250810,
          "stop" : 1727402278596,
          "duration" : 27786
        }
      }, {
        "uid" : "981b97bcd5cc4024",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/981b97bcd5cc4024",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//button[@data-test-active-link=\"Similar phrases\"]')\nStacktrace:\n#0 0x55fc01f9113a <unknown>\n#1 0x55fc01c775e0 <unknown>\n#2 0x55fc01cc6be8 <unknown>\n#3 0x55fc01cc6e81 <unknown>\n#4 0x55fc01d0d8c4 <unknown>\n#5 0x55fc01cebb4d <unknown>\n#6 0x55fc01d0ad7d <unknown>\n#7 0x55fc01ceb8c3 <unknown>\n#8 0x55fc01cb96b3 <unknown>\n#9 0x55fc01cba68e <unknown>\n#10 0x55fc01f5bb3b <unknown>\n#11 0x55fc01f5fac1 <unknown>\n#12 0x55fc01f48335 <unknown>\n#13 0x55fc01f60642 <unknown>\n#14 0x55fc01f2d49f <unknown>\n#15 0x55fc01f80038 <unknown>\n#16 0x55fc01f80203 <unknown>\n#17 0x55fc01f8ff8c <unknown>\n#18 0x7f465f694ac3 <unknown>",
        "time" : {
          "start" : 1727315731117,
          "stop" : 1727315751245,
          "duration" : 20128
        }
      }, {
        "uid" : "a22b896616247395",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/a22b896616247395",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Url: https://brainup.site/groups/4/series/10/subgroup/109/exercise/2960 has not been changed!!!",
        "time" : {
          "start" : 1727229344868,
          "stop" : 1727229369852,
          "duration" : 24984
        }
      }, {
        "uid" : "ea7a77fa50617fe0",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/ea7a77fa50617fe0",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//button[@data-test-active-link=\"Similar phrases\"]')\nStacktrace:\n#0 0x55cb2905b2da <unknown>\n#1 0x55cb28d29200 <unknown>\n#2 0x55cb28d78aa2 <unknown>\n#3 0x55cb28d78d41 <unknown>\n#4 0x55cb28dbe964 <unknown>\n#5 0x55cb28d9d8fd <unknown>\n#6 0x55cb28dbbdfd <unknown>\n#7 0x55cb28d9d673 <unknown>\n#8 0x55cb28d6b473 <unknown>\n#9 0x55cb28d6c47e <unknown>\n#10 0x55cb290220db <unknown>\n#11 0x55cb29026071 <unknown>\n#12 0x55cb2900e9d5 <unknown>\n#13 0x55cb29026bf2 <unknown>\n#14 0x55cb28ff3b6f <unknown>\n#15 0x55cb2904a248 <unknown>\n#16 0x55cb2904a417 <unknown>\n#17 0x55cb2905a0cc <unknown>\n#18 0x7f56cea94ac3 <unknown>",
        "time" : {
          "start" : 1727142883122,
          "stop" : 1727142903241,
          "duration" : 20119
        }
      }, {
        "uid" : "354f1c78b409e600",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/354f1c78b409e600",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727056298522,
          "stop" : 1727056306716,
          "duration" : 8194
        }
      }, {
        "uid" : "b743bc08d9a24802",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/40//#testresult/b743bc08d9a24802",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1726970228785,
          "stop" : 1726970237044,
          "duration" : 8259
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail" ]
  },
  "source" : "acf5be1c4b5a466e.json",
  "parameterValues" : [ ]
}