{
  "uid" : "b11cbedeca7d3bb3",
  "name" : "Select random card from \"Word\" group and compare UI vs BACKEND data",
  "fullName" : "tests.test_speech_exercises_en.TestCardsEN#test_random_word_cards_en",
  "historyId" : "84999af5e98c6318908a9abbfe6fc3a3",
  "time" : {
    "start" : 1728697347150,
    "stop" : 1728697347150,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55812984602a <unknown>\n#1 0x55812952c5e0 <unknown>\n#2 0x5581295247eb <unknown>\n#3 0x558129514a09 <unknown>\n#4 0x558129516744 <unknown>\n#5 0x558129514cbd <unknown>\n#6 0x55812951452f <unknown>\n#7 0x558129514422 <unknown>\n#8 0x558129512493 <unknown>\n#9 0x558129512ada <unknown>\n#10 0x55812952ef41 <unknown>\n#11 0x5581295c08c5 <unknown>\n#12 0x5581295a0b22 <unknown>\n#13 0x5581295bfd7d <unknown>\n#14 0x5581295a08c3 <unknown>\n#15 0x55812956e6b3 <unknown>\n#16 0x55812956f68e <unknown>\n#17 0x558129810a2b <unknown>\n#18 0x5581298149b1 <unknown>\n#19 0x5581297fd225 <unknown>\n#20 0x558129815532 <unknown>\n#21 0x5581297e238f <unknown>\n#22 0x558129834f28 <unknown>\n#23 0x5581298350f3 <unknown>\n#24 0x558129844e7c <unknown>\n#25 0x7ff512094ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"4419ba38400c1848f39012d4171ef6fc\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f4df4ec8f50>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x5581298350f3 \\\\u003Cunknown>\\\\n#24 0x558129844e7c \\\\u003Cunknown>\\\\n#25 0x7ff512094ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x55812984602a <unknown>\nE       #1 0x55812952c5e0 <unknown>\nE       #2 0x5581295247eb <unknown>\nE       #3 0x558129514a09 <unknown>\nE       #4 0x558129516744 <unknown>\nE       #5 0x558129514cbd <unknown>\nE       #6 0x55812951452f <unknown>\nE       #7 0x558129514422 <unknown>\nE       #8 0x558129512493 <unknown>\nE       #9 0x558129512ada <unknown>\nE       #10 0x55812952ef41 <unknown>\nE       #11 0x5581295c08c5 <unknown>\nE       #12 0x5581295a0b22 <unknown>\nE       #13 0x5581295bfd7d <unknown>\nE       #14 0x5581295a08c3 <unknown>\nE       #15 0x55812956e6b3 <unknown>\nE       #16 0x55812956f68e <unknown>\nE       #17 0x558129810a2b <unknown>\nE       #18 0x5581298149b1 <unknown>\nE       #19 0x5581297fd225 <unknown>\nE       #20 0x558129815532 <unknown>\nE       #21 0x5581297e238f <unknown>\nE       #22 0x558129834f28 <unknown>\nE       #23 0x5581298350f3 <unknown>\nE       #24 0x558129844e7c <unknown>\nE       #25 0x7ff512094ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728697347917,
      "stop" : 1728697348338,
      "duration" : 421
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55812984602a <unknown>\n#1 0x55812952c5e0 <unknown>\n#2 0x5581295247eb <unknown>\n#3 0x558129514a09 <unknown>\n#4 0x558129516744 <unknown>\n#5 0x558129514cbd <unknown>\n#6 0x55812951452f <unknown>\n#7 0x558129514422 <unknown>\n#8 0x558129512493 <unknown>\n#9 0x558129512ada <unknown>\n#10 0x55812952ef41 <unknown>\n#11 0x5581295c08c5 <unknown>\n#12 0x5581295a0b22 <unknown>\n#13 0x5581295bfd7d <unknown>\n#14 0x5581295a08c3 <unknown>\n#15 0x55812956e6b3 <unknown>\n#16 0x55812956f68e <unknown>\n#17 0x558129810a2b <unknown>\n#18 0x5581298149b1 <unknown>\n#19 0x5581297fd225 <unknown>\n#20 0x558129815532 <unknown>\n#21 0x5581297e238f <unknown>\n#22 0x558129834f28 <unknown>\n#23 0x5581298350f3 <unknown>\n#24 0x558129844e7c <unknown>\n#25 0x7ff512094ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728697347917,
        "stop" : 1728697348337,
        "duration" : 420
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55812984602a <unknown>\n#1 0x55812952c5e0 <unknown>\n#2 0x5581295247eb <unknown>\n#3 0x558129514a09 <unknown>\n#4 0x558129516744 <unknown>\n#5 0x558129514cbd <unknown>\n#6 0x55812951452f <unknown>\n#7 0x558129514422 <unknown>\n#8 0x558129512493 <unknown>\n#9 0x558129512ada <unknown>\n#10 0x55812952ef41 <unknown>\n#11 0x5581295c08c5 <unknown>\n#12 0x5581295a0b22 <unknown>\n#13 0x5581295bfd7d <unknown>\n#14 0x5581295a08c3 <unknown>\n#15 0x55812956e6b3 <unknown>\n#16 0x55812956f68e <unknown>\n#17 0x558129810a2b <unknown>\n#18 0x5581298149b1 <unknown>\n#19 0x5581297fd225 <unknown>\n#20 0x558129815532 <unknown>\n#21 0x5581297e238f <unknown>\n#22 0x558129834f28 <unknown>\n#23 0x5581298350f3 <unknown>\n#24 0x558129844e7c <unknown>\n#25 0x7ff512094ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"4419ba38400c1848f39012d4171ef6fc\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728697347151,
      "stop" : 1728697347917,
      "duration" : 766
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728697167335,
      "stop" : 1728697167335,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728697348372,
      "stop" : 1728697348434,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Speech exercises EN."
  }, {
    "name" : "epic",
    "value" : "Speech exercises."
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "subSuite",
    "value" : "TestCardsEN"
  }, {
    "name" : "host",
    "value" : "fv-az570-490"
  }, {
    "name" : "thread",
    "value" : "2304-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_speech_exercises_en"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 14,
        "passed" : 46,
        "unknown" : 0,
        "total" : 60
      },
      "items" : [ {
        "uid" : "3e24f6970eb55398",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/3e24f6970eb55398",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x563bd002e02a <unknown>\n#1 0x563bcfd145e0 <unknown>\n#2 0x563bcfd0c7eb <unknown>\n#3 0x563bcfcfca09 <unknown>\n#4 0x563bcfcfe744 <unknown>\n#5 0x563bcfcfccbd <unknown>\n#6 0x563bcfcfc52f <unknown>\n#7 0x563bcfcfc422 <unknown>\n#8 0x563bcfcfa493 <unknown>\n#9 0x563bcfcfaada <unknown>\n#10 0x563bcfd16f41 <unknown>\n#11 0x563bcfda88c5 <unknown>\n#12 0x563bcfd88b22 <unknown>\n#13 0x563bcfda7d7d <unknown>\n#14 0x563bcfd888c3 <unknown>\n#15 0x563bcfd566b3 <unknown>\n#16 0x563bcfd5768e <unknown>\n#17 0x563bcfff8a2b <unknown>\n#18 0x563bcfffc9b1 <unknown>\n#19 0x563bcffe5225 <unknown>\n#20 0x563bcfffd532 <unknown>\n#21 0x563bcffca38f <unknown>\n#22 0x563bd001cf28 <unknown>\n#23 0x563bd001d0f3 <unknown>\n#24 0x563bd002ce7c <unknown>\n#25 0x7f304de94ac3 <unknown>",
        "time" : {
          "start" : 1728611038325,
          "stop" : 1728611038325,
          "duration" : 0
        }
      }, {
        "uid" : "384aae14168ecae1",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/384aae14168ecae1",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728525085532,
          "stop" : 1728525095044,
          "duration" : 9512
        }
      }, {
        "uid" : "20270305efc07df0",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/20270305efc07df0",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728438756682,
          "stop" : 1728438766228,
          "duration" : 9546
        }
      }, {
        "uid" : "1cf1ead928b79a8a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/1cf1ead928b79a8a",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728352350108,
          "stop" : 1728352360921,
          "duration" : 10813
        }
      }, {
        "uid" : "5018b2ce829df01a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/5018b2ce829df01a",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728266947535,
          "stop" : 1728266947535,
          "duration" : 0
        }
      }, {
        "uid" : "8d66763eb4811989",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/8d66763eb4811989",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728179893410,
          "stop" : 1728179902880,
          "duration" : 9470
        }
      }, {
        "uid" : "997883f98f18d041",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/997883f98f18d041",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728093150617,
          "stop" : 1728093161195,
          "duration" : 10578
        }
      }, {
        "uid" : "14dad44d36305bc1",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/14dad44d36305bc1",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728006853854,
          "stop" : 1728006865971,
          "duration" : 12117
        }
      }, {
        "uid" : "ed0b85a229ba0a91",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/ed0b85a229ba0a91",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Url: https://brainup.site/groups/4/series/9/subgroup/78/exercise/2217 has not been changed!!!",
        "time" : {
          "start" : 1727920519372,
          "stop" : 1727920562195,
          "duration" : 42823
        }
      }, {
        "uid" : "2570c2e895e4094d",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/2570c2e895e4094d",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Url: https://brainup.site/groups/4/series/9 has not been changed!!!",
        "time" : {
          "start" : 1727833924155,
          "stop" : 1727833948628,
          "duration" : 24473
        }
      }, {
        "uid" : "9fb9cfe91b97cb6",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/9fb9cfe91b97cb6",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Url: https://brainup.site/groups/4/series/9/exercise/2228 has not been changed!!!",
        "time" : {
          "start" : 1727748049981,
          "stop" : 1727748089265,
          "duration" : 39284
        }
      }, {
        "uid" : "d9a845b5e4c42601",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/d9a845b5e4c42601",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Url: https://brainup.site/groups/4/series/9/exercise/2355 has not been changed!!!",
        "time" : {
          "start" : 1727661329624,
          "stop" : 1727661369412,
          "duration" : 39788
        }
      }, {
        "uid" : "93a7b91f3b3fdb5f",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/93a7b91f3b3fdb5f",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 'answerOptions'",
        "time" : {
          "start" : 1727575150153,
          "stop" : 1727575223674,
          "duration" : 73521
        }
      }, {
        "uid" : "9b9fba96c9a6409f",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/9b9fba96c9a6409f",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Url: https://brainup.site/groups/4/series/9/subgroup/87/exercise/2343 has not been changed!!!",
        "time" : {
          "start" : 1727488388844,
          "stop" : 1727488433442,
          "duration" : 44598
        }
      }, {
        "uid" : "f74fb0ff22fabc0a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/f74fb0ff22fabc0a",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//button[@data-test-active-link=\"Words\"]')\nStacktrace:\n#0 0x55dbb6d9c13a <unknown>\n#1 0x55dbb6a825e0 <unknown>\n#2 0x55dbb6ad1be8 <unknown>\n#3 0x55dbb6ad1e81 <unknown>\n#4 0x55dbb6b188c4 <unknown>\n#5 0x55dbb6af6b4d <unknown>\n#6 0x55dbb6b15d7d <unknown>\n#7 0x55dbb6af68c3 <unknown>\n#8 0x55dbb6ac46b3 <unknown>\n#9 0x55dbb6ac568e <unknown>\n#10 0x55dbb6d66b3b <unknown>\n#11 0x55dbb6d6aac1 <unknown>\n#12 0x55dbb6d53335 <unknown>\n#13 0x55dbb6d6b642 <unknown>\n#14 0x55dbb6d3849f <unknown>\n#15 0x55dbb6d8b038 <unknown>\n#16 0x55dbb6d8b203 <unknown>\n#17 0x55dbb6d9af8c <unknown>\n#18 0x7f46efc94ac3 <unknown>",
        "time" : {
          "start" : 1727402126187,
          "stop" : 1727402146318,
          "duration" : 20131
        }
      }, {
        "uid" : "b018c5ad8cc7ca37",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/b018c5ad8cc7ca37",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Url: https://brainup.site/groups/4/series/9/exercise/2555 has not been changed!!!",
        "time" : {
          "start" : 1727315635738,
          "stop" : 1727315690885,
          "duration" : 55147
        }
      }, {
        "uid" : "6cfa021f9f6cca1e",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/6cfa021f9f6cca1e",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727229228816,
          "stop" : 1727229243058,
          "duration" : 14242
        }
      }, {
        "uid" : "938d80bf5cd48a06",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/938d80bf5cd48a06",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//button[@data-test-active-link=\"Words\"]')\nStacktrace:\n#0 0x55aa2f7b62da <unknown>\n#1 0x55aa2f484200 <unknown>\n#2 0x55aa2f4d3aa2 <unknown>\n#3 0x55aa2f4d3d41 <unknown>\n#4 0x55aa2f519964 <unknown>\n#5 0x55aa2f4f88fd <unknown>\n#6 0x55aa2f516dfd <unknown>\n#7 0x55aa2f4f8673 <unknown>\n#8 0x55aa2f4c6473 <unknown>\n#9 0x55aa2f4c747e <unknown>\n#10 0x55aa2f77d0db <unknown>\n#11 0x55aa2f781071 <unknown>\n#12 0x55aa2f7699d5 <unknown>\n#13 0x55aa2f781bf2 <unknown>\n#14 0x55aa2f74eb6f <unknown>\n#15 0x55aa2f7a5248 <unknown>\n#16 0x55aa2f7a5417 <unknown>\n#17 0x55aa2f7b50cc <unknown>\n#18 0x7f6794294ac3 <unknown>",
        "time" : {
          "start" : 1727142756139,
          "stop" : 1727142776309,
          "duration" : 20170
        }
      }, {
        "uid" : "522f2de3328e4e7b",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/522f2de3328e4e7b",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727056269949,
          "stop" : 1727056278488,
          "duration" : 8539
        }
      }, {
        "uid" : "460e0a3b8e5b9c8a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/40//#testresult/460e0a3b8e5b9c8a",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1726970199638,
          "stop" : 1726970208511,
          "duration" : 8873
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail" ]
  },
  "source" : "b11cbedeca7d3bb3.json",
  "parameterValues" : [ ]
}