{
  "uid" : "9cacd451101ccbfe",
  "name" : "Verify presence and visibility of content on the page",
  "fullName" : "tests.used_resources_page_test.TestUsedResourcesPageForAuthorizedUserStructure#test_ur_01_01_verify_page_presence_and_visibility",
  "historyId" : "e7aa7276bca1f837fbcd28a0219d6113",
  "time" : {
    "start" : 1728611055193,
    "stop" : 1728611055193,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x56152406902a <unknown>\n#1 0x561523d4f5e0 <unknown>\n#2 0x561523d477eb <unknown>\n#3 0x561523d37a09 <unknown>\n#4 0x561523d39744 <unknown>\n#5 0x561523d37cbd <unknown>\n#6 0x561523d3752f <unknown>\n#7 0x561523d37422 <unknown>\n#8 0x561523d35493 <unknown>\n#9 0x561523d35ada <unknown>\n#10 0x561523d51f41 <unknown>\n#11 0x561523de38c5 <unknown>\n#12 0x561523dc3b22 <unknown>\n#13 0x561523de2d7d <unknown>\n#14 0x561523dc38c3 <unknown>\n#15 0x561523d916b3 <unknown>\n#16 0x561523d9268e <unknown>\n#17 0x561524033a2b <unknown>\n#18 0x5615240379b1 <unknown>\n#19 0x561524020225 <unknown>\n#20 0x561524038532 <unknown>\n#21 0x56152400538f <unknown>\n#22 0x561524057f28 <unknown>\n#23 0x5615240580f3 <unknown>\n#24 0x561524067e7c <unknown>\n#25 0x7f30a1094ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8f5c7c67a0bbb1234a31fd46a0680dab\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f3bf88f63f0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x5615240580f3 \\\\u003Cunknown>\\\\n#24 0x561524067e7c \\\\u003Cunknown>\\\\n#25 0x7f30a1094ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x56152406902a <unknown>\nE       #1 0x561523d4f5e0 <unknown>\nE       #2 0x561523d477eb <unknown>\nE       #3 0x561523d37a09 <unknown>\nE       #4 0x561523d39744 <unknown>\nE       #5 0x561523d37cbd <unknown>\nE       #6 0x561523d3752f <unknown>\nE       #7 0x561523d37422 <unknown>\nE       #8 0x561523d35493 <unknown>\nE       #9 0x561523d35ada <unknown>\nE       #10 0x561523d51f41 <unknown>\nE       #11 0x561523de38c5 <unknown>\nE       #12 0x561523dc3b22 <unknown>\nE       #13 0x561523de2d7d <unknown>\nE       #14 0x561523dc38c3 <unknown>\nE       #15 0x561523d916b3 <unknown>\nE       #16 0x561523d9268e <unknown>\nE       #17 0x561524033a2b <unknown>\nE       #18 0x5615240379b1 <unknown>\nE       #19 0x561524020225 <unknown>\nE       #20 0x561524038532 <unknown>\nE       #21 0x56152400538f <unknown>\nE       #22 0x561524057f28 <unknown>\nE       #23 0x5615240580f3 <unknown>\nE       #24 0x561524067e7c <unknown>\nE       #25 0x7f30a1094ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver",
    "time" : {
      "start" : 1728611055194,
      "stop" : 1728611055957,
      "duration" : 763
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728611055957,
      "stop" : 1728611056381,
      "duration" : 424
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x56152406902a <unknown>\n#1 0x561523d4f5e0 <unknown>\n#2 0x561523d477eb <unknown>\n#3 0x561523d37a09 <unknown>\n#4 0x561523d39744 <unknown>\n#5 0x561523d37cbd <unknown>\n#6 0x561523d3752f <unknown>\n#7 0x561523d37422 <unknown>\n#8 0x561523d35493 <unknown>\n#9 0x561523d35ada <unknown>\n#10 0x561523d51f41 <unknown>\n#11 0x561523de38c5 <unknown>\n#12 0x561523dc3b22 <unknown>\n#13 0x561523de2d7d <unknown>\n#14 0x561523dc38c3 <unknown>\n#15 0x561523d916b3 <unknown>\n#16 0x561523d9268e <unknown>\n#17 0x561524033a2b <unknown>\n#18 0x5615240379b1 <unknown>\n#19 0x561524020225 <unknown>\n#20 0x561524038532 <unknown>\n#21 0x56152400538f <unknown>\n#22 0x561524057f28 <unknown>\n#23 0x5615240580f3 <unknown>\n#24 0x561524067e7c <unknown>\n#25 0x7f30a1094ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728611055958,
        "stop" : 1728611056381,
        "duration" : 423
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x56152406902a <unknown>\n#1 0x561523d4f5e0 <unknown>\n#2 0x561523d477eb <unknown>\n#3 0x561523d37a09 <unknown>\n#4 0x561523d39744 <unknown>\n#5 0x561523d37cbd <unknown>\n#6 0x561523d3752f <unknown>\n#7 0x561523d37422 <unknown>\n#8 0x561523d35493 <unknown>\n#9 0x561523d35ada <unknown>\n#10 0x561523d51f41 <unknown>\n#11 0x561523de38c5 <unknown>\n#12 0x561523dc3b22 <unknown>\n#13 0x561523de2d7d <unknown>\n#14 0x561523dc38c3 <unknown>\n#15 0x561523d916b3 <unknown>\n#16 0x561523d9268e <unknown>\n#17 0x561524033a2b <unknown>\n#18 0x5615240379b1 <unknown>\n#19 0x561524020225 <unknown>\n#20 0x561524038532 <unknown>\n#21 0x56152400538f <unknown>\n#22 0x561524057f28 <unknown>\n#23 0x5615240580f3 <unknown>\n#24 0x561524067e7c <unknown>\n#25 0x7f30a1094ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"8f5c7c67a0bbb1234a31fd46a0680dab\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728610900918,
      "stop" : 1728610900918,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728611056414,
      "stop" : 1728611056476,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Test Used Resources Page"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "used_resources_page_test"
  }, {
    "name" : "subSuite",
    "value" : "TestUsedResourcesPage"
  }, {
    "name" : "host",
    "value" : "fv-az740-570"
  }, {
    "name" : "thread",
    "value" : "2375-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.used_resources_page_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 25,
        "unknown" : 0,
        "total" : 29
      },
      "items" : [ {
        "uid" : "6489ff71b8a8b678",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/6489ff71b8a8b678",
        "status" : "passed",
        "time" : {
          "start" : 1728525336710,
          "stop" : 1728525337491,
          "duration" : 781
        }
      }, {
        "uid" : "39269f5784cd6b2c",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/39269f5784cd6b2c",
        "status" : "passed",
        "time" : {
          "start" : 1728439166848,
          "stop" : 1728439167626,
          "duration" : 778
        }
      }, {
        "uid" : "5b3293a9b81a9708",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/5b3293a9b81a9708",
        "status" : "passed",
        "time" : {
          "start" : 1728352609215,
          "stop" : 1728352610010,
          "duration" : 795
        }
      }, {
        "uid" : "f19488830f14df5",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/f19488830f14df5",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728267537939,
          "stop" : 1728267537939,
          "duration" : 0
        }
      }, {
        "uid" : "c0f03cb6162b9e67",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/c0f03cb6162b9e67",
        "status" : "passed",
        "time" : {
          "start" : 1728180145519,
          "stop" : 1728180146315,
          "duration" : 796
        }
      }, {
        "uid" : "5cd3204e08a3442b",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/5cd3204e08a3442b",
        "status" : "passed",
        "time" : {
          "start" : 1728093436799,
          "stop" : 1728093437649,
          "duration" : 850
        }
      }, {
        "uid" : "e3f362357e54e67b",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/e3f362357e54e67b",
        "status" : "passed",
        "time" : {
          "start" : 1728007142463,
          "stop" : 1728007143308,
          "duration" : 845
        }
      }, {
        "uid" : "60d42ecd7c29a089",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/60d42ecd7c29a089",
        "status" : "passed",
        "time" : {
          "start" : 1727921006335,
          "stop" : 1727921007203,
          "duration" : 868
        }
      }, {
        "uid" : "da9260d15c63cf53",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/da9260d15c63cf53",
        "status" : "passed",
        "time" : {
          "start" : 1727834317751,
          "stop" : 1727834318542,
          "duration" : 791
        }
      }, {
        "uid" : "552489905f4d14b9",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/552489905f4d14b9",
        "status" : "passed",
        "time" : {
          "start" : 1727748472342,
          "stop" : 1727748473143,
          "duration" : 801
        }
      }, {
        "uid" : "88315d48bb2b6af7",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/88315d48bb2b6af7",
        "status" : "passed",
        "time" : {
          "start" : 1727661727963,
          "stop" : 1727661728749,
          "duration" : 786
        }
      }, {
        "uid" : "73be263a8730f865",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/73be263a8730f865",
        "status" : "passed",
        "time" : {
          "start" : 1727575645065,
          "stop" : 1727575645855,
          "duration" : 790
        }
      }, {
        "uid" : "7d1c9a04e390c904",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/7d1c9a04e390c904",
        "status" : "passed",
        "time" : {
          "start" : 1727488981507,
          "stop" : 1727488982289,
          "duration" : 782
        }
      }, {
        "uid" : "21627741e0f4ead4",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/21627741e0f4ead4",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1727402626427,
          "stop" : 1727402626427,
          "duration" : 0
        }
      }, {
        "uid" : "a204ed7233ce201a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/a204ed7233ce201a",
        "status" : "passed",
        "time" : {
          "start" : 1727316230831,
          "stop" : 1727316231683,
          "duration" : 852
        }
      }, {
        "uid" : "9bb84d2fe68348d8",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/9bb84d2fe68348d8",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1727229785923,
          "stop" : 1727229785923,
          "duration" : 0
        }
      }, {
        "uid" : "cbbded942b1d3dc1",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/cbbded942b1d3dc1",
        "status" : "passed",
        "time" : {
          "start" : 1727143173065,
          "stop" : 1727143173865,
          "duration" : 800
        }
      }, {
        "uid" : "28c896dd1302c764",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/28c896dd1302c764",
        "status" : "passed",
        "time" : {
          "start" : 1727056606554,
          "stop" : 1727056607328,
          "duration" : 774
        }
      }, {
        "uid" : "a5bc8a74ab013916",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/40//#testresult/a5bc8a74ab013916",
        "status" : "passed",
        "time" : {
          "start" : 1726970428876,
          "stop" : 1726970429652,
          "duration" : 776
        }
      }, {
        "uid" : "2d3690804f8542e3",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/39//#testresult/2d3690804f8542e3",
        "status" : "passed",
        "time" : {
          "start" : 1726883608637,
          "stop" : 1726883609416,
          "duration" : 779
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "9cacd451101ccbfe.json",
  "parameterValues" : [ ]
}